# Objective
- Be able to filter specific rows in pandas using conditions, and analyze or save the filtered results.
---
# Key Concepts
* **Creating Conditions**: Writing boolean expressions to evaluate each row (True/False)
* **Saving Conditions to Variables**: Storing boolean masks in variables for cleaner code
* **Filtering with a Single Condition**: Extracting rows that meet a single criteria
* **Filtering with Multiple Conditions**: Combining multiple conditions using logical operators (`&` for AND, `|` for OR)
* **Filtering with String Conditions**: Extracting rows based on text patterns (e.g., `.str.contains()`)
* **`isin()`**: Filtering rows where a column's value matches any element in a specific list
* **`between()`**: Extracting rows with numerical values falling within a specific range (inclusive)
* **`~` (NOT Condition)**: Inverting a condition to select rows that do not match the criteria
* **Saving Filtered Results**: Assigning the filtered DataFrame to a new variable or exporting it to a file

---
## 01. Conditional Filtering
- Filter rows based on a specific boolean condition.

### &nbsp;&nbsp;&nbsp;&nbsp;Example: Employee Dataset
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Let's assume we have the following employee dataset:
| Name | Department | Experience | Score | Status |
| :--- | :--- | :---: | :---: | :--- |
| Alice | Engineering | 5 | 88 | Active |
| Bob | Data | 3 | 92 | Active |
| Charlie | Engineering | 7 | 79 | Inactive |
| David | Cloud | 4 | 85 | Active |
| Eva | Data | 2 | 67 | Inactive |
| Frank | Security | 8 | 95 | Active |

#### &nbsp;&nbsp;&nbsp;&nbsp;Filtering Rows with a Condition
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If you want to view only the employees whose **Score is 85 or higher**, you can apply the condition inside the brackets like this:

```python
# Filter the DataFrame for employees with a Score >= 85
df[df["Score"] >= 85]
```

In [2]:
import pandas as pd
import os

input_dir = "../assets/Week06/Day02/Input"
input_file = "emplyee_performance.csv"
output_dir = "../assets/Week06/Day02/Output"

os.makedirs(input_dir, exist_ok=True)
os.makedirs(output_dir, exist_ok=True)

employee_data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Henry"],
    "Department": ["Engineering", "Data", "Engineering", "Cloud", "Data", "Security", "Cloud", "Engineering"],
    "Experience": [5, 3, 7, 4, 2, 8, 6, 1],
    "Score": [88, 92, 79, 85, 67, 95, 90, 72],
    "Status": ["Active", "Active", "Inactive", "Active", "Inactive", "Active", "Active", "Inactive"],
    "Remote": [True, True, False, True, False, False, True, True]
}

df_employees = pd.DataFrame(employee_data)

df_employees.to_csv(f"{input_dir}/{input_file}", index=False)

if os.path.exists(f"{input_dir}/{input_file}"):
    print(f"{input_file} has been created.")
else:
    print(f"Error - Fail to create the input .csv file.")

emplyee_performance.csv has been created.

## 02. Understanding Boolean Conditions
- In pandas, filtering is a two-step process. First, you define a rule that generates True or False for each row. Then, pandas uses this rule to pull out only the `'True'` rows.

In [3]:
df_employees[ df_employees["Score"]>=85 ]

    Name   Department  Experience  Score  Status  Remote
0  Alice  Engineering           5     88  Active    True
1    Bob         Data           3     92  Active    True
3  David        Cloud           4     85  Active    True
5  Frank     Security           8     95  Active   False
6  Grace        Cloud           6     90  Active    True

## 03. Saving Conditions to Variables
- Keeping your conditions in separate variables makes your code much cleaner and easier to read as they get longer. This is a great habit to form for when you start dealing with advanced filtering later on.

In [4]:
# Create a condition
high_score_condition = df_employees["Score"] >= 85

# Use the condition for filtering
high_score_employees = df_employees[high_score_condition]

high_score_employees

    Name   Department  Experience  Score  Status  Remote
0  Alice  Engineering           5     88  Active    True
1    Bob         Data           3     92  Active    True
3  David        Cloud           4     85  Active    True
5  Frank     Security           8     95  Active   False
6  Grace        Cloud           6     90  Active    True

## 04. Save the filtered results in a csv file.

In [11]:
# Save high score employees as a CSV file
high_score_employees.to_csv(
    "../assets/Week06/Day02/Output/high_performers.csv",
    index=False
)

print("high_performers.csv has been saved.")

high_performers.csv has been saved.

In [12]:
# Filter Engineering employees with Score greater than or equal to 80
engineering_high_scores = df_employees[
    (df_employees["Department"] == "Engineering") & (df_employees["Score"] >= 80)
]

# Save the filtered result
engineering_high_scores.to_csv(
    "../assets/Week06/Day02/Output/engineering_high_scores.csv",
    index=False
)

print("engineering_high_scores.csv has been saved.")

engineering_high_scores.csv has been saved.

## 05. Practice Problems

### Practice 1 — Create a Sample CSV File
#### Goal: Practice creating a CSV file for conditional filtering.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Create a DataFrame with the following columns:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Name<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Department<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Experience<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Score<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Status<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Remote<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;Use at least eight rows of data.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Save it as:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;../assets/Week06/Day02/Input/employee_performance.csv

In [15]:
import pandas as pd
import os

input_dir = "../assets/Week06/Day02/Input"
input_file = "emplyee_performance.csv"
output_dir = "../assets/Week06/Day02/Output"

os.makedirs(input_dir, exist_ok=True)
os.makedirs(output_dir, exist_ok=True)

employee_data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Henry"],
    "Department": ["Engineering", "Data", "Engineering", "Cloud", "Data", "Security", "Cloud", "Engineering"],
    "Experience": [5, 3, 7, 4, 2, 8, 6, 1],
    "Score": [88, 92, 79, 85, 67, 95, 90, 72],
    "Status": ["Active", "Active", "Inactive", "Active", "Inactive", "Active", "Active", "Inactive"],
    "Remote": [True, True, False, True, False, False, True, True]
}

df_employees = pd.DataFrame(employee_data)

df_employees.to_csv(f"{input_dir}/{input_file}", index=False)

if os.path.exists(f"{input_dir}/{input_file}"):
    print(f"{input_file} has been created.")
else:
    print(f"Error - Fail to create the input .csv file.")

emplyee_performance.csv has been created.

### Practice 2 — Read the CSV File
#### Goal: Practice reading a CSV file before filtering data.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Read the following file:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;../assets/Week06/Day02/Input/employee_performance.csv<br>
&nbsp;&nbsp;&nbsp;&nbsp;Store it in df_employees.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Display the DataFrame.<br>

In [16]:
df_employees = pd.read_csv(f"{input_dir}/{input_file}")

df_employees

      Name   Department  Experience  Score    Status  Remote
0    Alice  Engineering           5     88    Active    True
1      Bob         Data           3     92    Active    True
2  Charlie  Engineering           7     79  Inactive   False
3    David        Cloud           4     85    Active    True
4      Eva         Data           2     67  Inactive   False
5    Frank     Security           8     95    Active   False
6    Grace        Cloud           6     90    Active    True
7    Henry  Engineering           1     72  Inactive    True

### Practice 3 — Filter High Score Employees
#### Goal: Practice filtering rows using one numeric condition.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Select employees whose Score is greater than or equal to 85.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Store the result in high_score_employees.

In [17]:
high_score_employees = df_employees[ df_employees["Score"]>=85 ]
high_score_employees

    Name   Department  Experience  Score  Status  Remote
0  Alice  Engineering           5     88  Active    True
1    Bob         Data           3     92  Active    True
3  David        Cloud           4     85  Active    True
5  Frank     Security           8     95  Active   False
6  Grace        Cloud           6     90  Active    True

### Practice 4 — Filter Active Employees
#### Goal: Practice filtering rows using one string condition.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Select employees whose Status is "Active".<br>
&nbsp;&nbsp;&nbsp;&nbsp;Store the result in active_employees.

In [18]:
active_employees = df_employees[ df_employees["Status"] == "Active" ]
active_employees

    Name   Department  Experience  Score  Status  Remote
0  Alice  Engineering           5     88  Active    True
1    Bob         Data           3     92  Active    True
3  David        Cloud           4     85  Active    True
5  Frank     Security           8     95  Active   False
6  Grace        Cloud           6     90  Active    True

### Practice 5 — Filter with Multiple Conditions
#### Goal: Practice using & for multiple conditions.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Select employees whose:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Score is greater than or equal to 85<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;AND<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Status is Active<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;Store the result in high_active_employees.<br>

In [19]:
high_active_employees = df_employees[ (df_employees["Score"]>85) & (df_employees["Status"]=="Active") ]
high_active_employees

    Name   Department  Experience  Score  Status  Remote
0  Alice  Engineering           5     88  Active    True
1    Bob         Data           3     92  Active    True
5  Frank     Security           8     95  Active   False
6  Grace        Cloud           6     90  Active    True

### Practice 6 — Filter with OR Condition
#### Goal: Practice using | for OR conditions.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Select employees whose Department is either "Data" or "Cloud".<br>
&nbsp;&nbsp;&nbsp;&nbsp;Store the result in data_or_cloud_employees.

In [20]:
data_or_cloud_employees = df_employees[ (df_employees["Department"]=="Data") | (df_employees["Department"]=="Cloud") ]
data_or_cloud_employees

    Name Department  Experience  Score    Status  Remote
1    Bob       Data           3     92    Active    True
3  David      Cloud           4     85    Active    True
4    Eva       Data           2     67  Inactive   False
6  Grace      Cloud           6     90    Active    True

### Practice 7 — Filter with isin()
#### Goal: Practice filtering rows using isin().
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Select employees whose Department is one of:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Engineering<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Data<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cloud<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;Store the result in selected_departments.

In [25]:
selected_departments = df_employees[ df_employees["Department"].isin( ["Engineering", "Data", "Cloud"] ) ]
selected_departments

      Name   Department  Experience  Score    Status  Remote
0    Alice  Engineering           5     88    Active    True
1      Bob         Data           3     92    Active    True
2  Charlie  Engineering           7     79  Inactive   False
3    David        Cloud           4     85    Active    True
4      Eva         Data           2     67  Inactive   False
6    Grace        Cloud           6     90    Active    True
7    Henry  Engineering           1     72  Inactive    True

### Practice 8 — Filter with between()
#### Goal: Practice filtering numeric values within a range.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Select employees whose Score is between 80 and 90.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Store the result in score_between_80_90.

In [26]:
score_between_80_90 = df_employees[ df_employees["Score"].between(80, 90) ]
score_between_80_90

    Name   Department  Experience  Score  Status  Remote
0  Alice  Engineering           5     88  Active    True
3  David        Cloud           4     85  Active    True
6  Grace        Cloud           6     90  Active    True

### Practice 9 — Filter Remote Employees
#### Goal: Practice filtering rows using a boolean column.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Select employees whose Remote value is True.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Store the result in remote_employees.

In [29]:
remote_employees = df_employees[ df_employees["Remote"] ]

remote_employees

    Name   Department  Experience  Score    Status  Remote
0  Alice  Engineering           5     88    Active    True
1    Bob         Data           3     92    Active    True
3  David        Cloud           4     85    Active    True
6  Grace        Cloud           6     90    Active    True
7  Henry  Engineering           1     72  Inactive    True

### Practice 10 — Filter and Select Columns with loc[]
#### Goal: Practice filtering rows and selecting columns at the same time.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Select employees whose Score is greater than or equal to 85.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Return only:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Name<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Department<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Score<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;Store the result in high_score_summary.

In [32]:
high_score_summary = df_employees.loc[ df_employees["Score"]>=85, ["Name", "Department", "Score"] ]
high_score_summary

    Name   Department  Score
0  Alice  Engineering     88
1    Bob         Data     92
3  David        Cloud     85
5  Frank     Security     95
6  Grace        Cloud     90

### Practice 11 — Save Filtered Results
#### Goal: Practice saving filtered DataFrames as CSV files.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Save high_score_employees as:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;../assets/Week06/Day02/Output/high_performers.csv<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;Save employees whose Department is "Engineering" and Score is greater than or equal to 80 as:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;../assets/Week06/Day02/Output/engineering_high_scores.csv

In [34]:
high_score_employees.to_csv( f"{output_dir}/high_performers.csv", index=False )

engineering_high_scores = df_employees[ (df_employees["Department"] == "Engineering") & (df_employees["Score"]>=80) ]

high_score_employees.to_csv( f"{output_dir}/engineering_high_scores.csv", index=False )

## Summary

Today, I practiced conditional filtering in pandas.

I created a sample employee performance dataset and saved it as a CSV file. Then, I loaded the CSV file back into a pandas DataFrame for filtering practice.

I learned how to create boolean conditions from DataFrame columns and use those conditions to filter rows.

I practiced filtering rows using numeric conditions, string conditions, boolean columns, multiple conditions with `&`, OR conditions with `|`, `isin()`, and `between()`.

I also practiced using `.loc[]` to filter rows and select specific columns at the same time.

Finally, I saved filtered DataFrames as CSV files, including high-performing employees and Engineering employees with high scores.

These concepts are important because conditional filtering helps select meaningful subsets of data for analysis, reporting, and machine learning workflows.