# **Objective:**
- Be able to add a new column to a pandas DataFrame and create calculated, conditional, or categorized columns using existing column values.

## Today's Key Concepts
* **Adding a New Column Directly**: Assigning a scalar value or an array to a new column label
* **Creating Calculated Columns Using Existing Columns**: Performing vector arithmetic between existing columns to derive a new one
* **Assigning Column Values Based on Conditions**: Populating a column with different values depending on conditional logic
* **Creating Boolean Columns**: Generating columns that store `True` or `False` based on logical expressions
* **Creating String Columns**: Creating columns containing text data or applying string methods to format text
* **Modifying Conditional Column Values with `.loc[]`**: Using label-based indexing to selectively update specific rows in a column
* **Saving a DataFrame with Newly Added Columns**: Persisting the updated DataFrame by exporting it to a file or assigning it back

In [2]:
# pre seting
# Import modules
import os
import pandas as pd

# Create input and output folders
input_dir = "../assets/Week06/Day03/Input"
input_file = "employee_performance.csv"
output_dir = "../assets/Week06/Day03/Output"

os.makedirs(input_dir, exist_ok=True)
os.makedirs(output_dir, exist_ok=True)

# Create sample employee performance data
employee_data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Henry"],
    "Department": ["Engineering", "Data", "Engineering", "Cloud", "Data", "Security", "Cloud", "Engineering"],
    "Experience": [5, 3, 7, 4, 2, 8, 6, 1],
    "Score": [88, 92, 79, 85, 67, 95, 90, 72],
    "Status": ["Active", "Active", "Inactive", "Active", "Inactive", "Active", "Active", "Inactive"],
    "Remote": [True, True, False, True, False, False, True, True]
}

# Create a DataFrame
df_employees = pd.DataFrame(employee_data)

# Save the DataFrame as a CSV file
df_employees.to_csv(f"{input_dir}/{input_file}", index=False)

print("employee_performance.csv has been created.")

# Read the employee performance CSV file
df_employees = pd.read_csv("../assets/Week06/Day03/Input/employee_performance.csv")

# Display the DataFrame
df_employees

employee_performance.csv has been created.

      Name   Department  Experience  Score    Status  Remote
0    Alice  Engineering           5     88    Active    True
1      Bob         Data           3     92    Active    True
2  Charlie  Engineering           7     79  Inactive   False
3    David        Cloud           4     85    Active    True
4      Eva         Data           2     67  Inactive   False
5    Frank     Security           8     95    Active   False
6    Grace        Cloud           6     90    Active    True
7    Henry  Engineering           1     72  Inactive    True

---
## 01. Adding a New Column with a Constant Value
- You can create a column that holds the same value for every single row. When you assign a scalar value, it is automatically populated across all rows.

In [4]:
# Add a new column with the same value for all rows
df_employees["Company"] = "ABC Tech"

df_employees

      Name   Department  Experience  Score    Status  Remote   Company
0    Alice  Engineering           5     88    Active    True  ABC Tech
1      Bob         Data           3     92    Active    True  ABC Tech
2  Charlie  Engineering           7     79  Inactive   False  ABC Tech
3    David        Cloud           4     85    Active    True  ABC Tech
4      Eva         Data           2     67  Inactive   False  ABC Tech
5    Frank     Security           8     95    Active   False  ABC Tech
6    Grace        Cloud           6     90    Active    True  ABC Tech
7    Henry  Engineering           1     72  Inactive    True  ABC Tech

---
## 02. Create a new calculated column using existing column values
- You can derive a new column by performing mathematical operations on existing column values. Pandas applies this vectorized arithmetic across all rows instantly.

In [5]:
# Create a new column based on the Score column
df_employees["Score_Percentage"] = df_employees["Score"] / 100

df_employees

,Name,Department,Experience,Score,Status,Remote,Company,Score_Percentage
0,Alice,Engineering,5,88,Active,True,ABC Tech,0.88
1,Bob,Data,3,92,Active,True,ABC Tech,0.92
2,Charlie,Engineering,7,79,Inactive,False,ABC Tech,0.79
3,David,Cloud,4,85,Active,True,ABC Tech,0.85
4,Eva,Data,2,67,Inactive,False,ABC Tech,0.67
5,Frank,Security,8,95,Active,False,ABC Tech,0.95
6,Grace,Cloud,6,90,Active,True,ABC Tech,0.90
7,Henry,Engineering,1,72,Inactive,True,ABC Tech,0.72

In [6]:
# Convert years of experience to months
df_employees["Experience_Months"] = df_employees["Experience"] * 12

df_employees

,Name,Department,Experience,Score,Status,Remote,Company,Score_Percentage,Experience_Months
0,Alice,Engineering,5,88,Active,True,ABC Tech,0.88,60
1,Bob,Data,3,92,Active,True,ABC Tech,0.92,36
2,Charlie,Engineering,7,79,Inactive,False,ABC Tech,0.79,84
3,David,Cloud,4,85,Active,True,ABC Tech,0.85,48
4,Eva,Data,2,67,Inactive,False,ABC Tech,0.67,24
5,Frank,Security,8,95,Active,False,ABC Tech,0.95,96
6,Grace,Cloud,6,90,Active,True,ABC Tech,0.90,72
7,Henry,Engineering,1,72,Inactive,True,ABC Tech,0.72,12

---
## 03. Create a boolean column based on a conditional expression
- You can store the results of a conditional expression as a new column. This creates a Boolean column containing True or False values for each row based on the criteria.

In [7]:
# Create a boolean column based on Score
df_employees["High_Performer"] = df_employees["Score"] >= 85

df_employees

,Name,Department,Experience,Score,Status,Remote,Company,Score_Percentage,Experience_Months,High_Performer
0,Alice,Engineering,5,88,Active,True,ABC Tech,0.88,60,True
1,Bob,Data,3,92,Active,True,ABC Tech,0.92,36,True
2,Charlie,Engineering,7,79,Inactive,False,ABC Tech,0.79,84,False
3,David,Cloud,4,85,Active,True,ABC Tech,0.85,48,True
4,Eva,Data,2,67,Inactive,False,ABC Tech,0.67,24,False
5,Frank,Security,8,95,Active,False,ABC Tech,0.95,96,True
6,Grace,Cloud,6,90,Active,True,ABC Tech,0.90,72,True
7,Henry,Engineering,1,72,Inactive,True,ABC Tech,0.72,12,False

- These boolean columns can be used directly as a boolean mask for filtering the DataFrame later

In [8]:
# Filter only high performers
high_performers = df_employees[df_employees["High_Performer"]]

high_performers

,Name,Department,Experience,Score,Status,Remote,Company,Score_Percentage,Experience_Months,High_Performer
0,Alice,Engineering,5,88,Active,True,ABC Tech,0.88,60,True
1,Bob,Data,3,92,Active,True,ABC Tech,0.92,36,True
3,David,Cloud,4,85,Active,True,ABC Tech,0.85,48,True
5,Frank,Security,8,95,Active,False,ABC Tech,0.95,96,True
6,Grace,Cloud,6,90,Active,True,ABC Tech,0.90,72,True

---
## 04. Assign values conditionally

In [13]:
###########################
# >= 90: Excellent        #
# < 90, >= 80: Good       #
# < 70, >= 70: Average    #
# < 70: Needs Improvement #
###########################

# Create a default score level column
df_employees["Score_Level"] = "Needs Improvement"

# Update Score_Level based on Score conditions
df_employees.loc[df_employees["Score"] >= 70, "Score_Level"] = "Average"
df_employees.loc[df_employees["Score"] >= 80, "Score_Level"] = "Good"
df_employees.loc[df_employees["Score"] >= 90, "Score_Level"] = "Excellent"

df_employees

,Name,Department,Experience,Score,Status,Remote,Company,Score_Percentage,Experience_Months,High_Performer,Score_Level
0,Alice,Engineering,5,88,Active,True,ABC Tech,0.88,60,True,Good
1,Bob,Data,3,92,Active,True,ABC Tech,0.92,36,True,Excellent
2,Charlie,Engineering,7,79,Inactive,False,ABC Tech,0.79,84,False,Average
3,David,Cloud,4,85,Active,True,ABC Tech,0.85,48,True,Good
4,Eva,Data,2,67,Inactive,False,ABC Tech,0.67,24,False,Needs Improvement
5,Frank,Security,8,95,Active,False,ABC Tech,0.95,96,True,Excellent
6,Grace,Cloud,6,90,Active,True,ABC Tech,0.90,72,True,Excellent
7,Henry,Engineering,1,72,Inactive,True,ABC Tech,0.72,12,False,Average

---
## 05. Assign values based on a combination of multiple conditions

In [14]:
# e.g.)
# Score >= 85 AND Status == Active

# Create a bonus eligibility column using multiple conditions
df_employees["Bonus_Eligible"] = (
    (df_employees["Score"] >= 85) & 
    (df_employees["Status"] == "Active")
)

df_employees

,Name,Department,Experience,Score,Status,Remote,Company,Score_Percentage,Experience_Months,High_Performer,Score_Level,Bonus_Eligible
0,Alice,Engineering,5,88,Active,True,ABC Tech,0.88,60,True,Good,True
1,Bob,Data,3,92,Active,True,ABC Tech,0.92,36,True,Excellent,True
2,Charlie,Engineering,7,79,Inactive,False,ABC Tech,0.79,84,False,Average,False
3,David,Cloud,4,85,Active,True,ABC Tech,0.85,48,True,Good,True
4,Eva,Data,2,67,Inactive,False,ABC Tech,0.67,24,False,Needs Improvement,False
5,Frank,Security,8,95,Active,False,ABC Tech,0.95,96,True,Excellent,True
6,Grace,Cloud,6,90,Active,True,ABC Tech,0.90,72,True,Excellent,True
7,Henry,Engineering,1,72,Inactive,True,ABC Tech,0.72,12,False,Average,False

---
## 06. Concatenate multiple string columns to create a custom text feature

In [15]:
# Create an employee label using Name and Department
df_employees["Employee_Label"] = df_employees["Name"] + " - " + df_employees["Department"]

df_employees

,Name,Department,Experience,Score,Status,Remote,Company,Score_Percentage,Experience_Months,High_Performer,Score_Level,Bonus_Eligible,Employee_Label
0,Alice,Engineering,5,88,Active,True,ABC Tech,0.88,60,True,Good,True,Alice - Engineering
1,Bob,Data,3,92,Active,True,ABC Tech,0.92,36,True,Excellent,True,Bob - Data
2,Charlie,Engineering,7,79,Inactive,False,ABC Tech,0.79,84,False,Average,False,Charlie - Engineering
3,David,Cloud,4,85,Active,True,ABC Tech,0.85,48,True,Good,True,David - Cloud
4,Eva,Data,2,67,Inactive,False,ABC Tech,0.67,24,False,Needs Improvement,False,Eva - Data
5,Frank,Security,8,95,Active,False,ABC Tech,0.95,96,True,Excellent,True,Frank - Security
6,Grace,Cloud,6,90,Active,True,ABC Tech,0.90,72,True,Excellent,True,Grace - Cloud
7,Henry,Engineering,1,72,Inactive,True,ABC Tech,0.72,12,False,Average,False,Henry - Engineering

## 07. Use .copy() to add a new column after filtering
- If you filter rows and immediately try to add a new column, pandas will get confused and show a warning. To avoid this, append .copy() to your filtering code so you can work on a fresh, safe copy of the data

```python
# BAD CASE: Triggers SettingWithCopyWarning
engineering_staff = df_employees[df_employees["Department"] == "Engineering"]
engineering_staff["Bonus_Rate"] = 0.15  # Warning raised here!

# GOOD CASE: Clean, safe, and correct approach
engineering_staff = df_employees[df_employees["Department"] == "Engineering"].copy()
engineering_staff["Bonus_Rate"] = 0.15  # Works perfectly without any warnings
```

In [16]:
# Filter high score employees and create a copy
high_score_employees = df_employees[df_employees["Score"] >= 85].copy()

# Add a new column to the copied DataFrame
high_score_employees["Review_Note"] = "High score review needed"

high_score_employees

,Name,Department,Experience,Score,Status,Remote,Company,Score_Percentage,Experience_Months,High_Performer,Score_Level,Bonus_Eligible,Employee_Label,Review_Note
0,Alice,Engineering,5,88,Active,True,ABC Tech,0.88,60,True,Good,True,Alice - Engineering,High score review needed
1,Bob,Data,3,92,Active,True,ABC Tech,0.92,36,True,Excellent,True,Bob - Data,High score review needed
3,David,Cloud,4,85,Active,True,ABC Tech,0.85,48,True,Good,True,David - Cloud,High score review needed
5,Frank,Security,8,95,Active,False,ABC Tech,0.95,96,True,Excellent,True,Frank - Security,High score review needed
6,Grace,Cloud,6,90,Active,True,ABC Tech,0.90,72,True,Excellent,True,Grace - Cloud,High score review needed

---
## 08. Saving the Results with the New Columns

In [18]:
# Save the DataFrame with new columns
df_employees.to_csv(
    "../assets/Week06/Day03/Output/employee_with_new_columns.csv",
    index=False
)

print("employee_with_new_columns.csv has been saved.")

employee_with_new_columns.csv has been saved.

In [19]:
# Filter bonus eligible employees
high_score_bonus_employees = df_employees[df_employees["Bonus_Eligible"]].copy()

# Save filtered result
high_score_bonus_employees.to_csv(
    "../assets/Week06/Day03/Output/high_score_bonus_employees.csv",
    index=False
)

print("high_score_bonus_employees.csv has been saved.")

high_score_bonus_employees.csv has been saved.

## Practice Problems

In [21]:
# pre seting
# Import modules
import os
import pandas as pd

# Create input and output folders
input_dir = "../assets/Week06/Day03/Input"
input_file = "employee_performance.csv"
output_dir = "../assets/Week06/Day03/Output"

os.makedirs(input_dir, exist_ok=True)
os.makedirs(output_dir, exist_ok=True)

# Create sample employee performance data
employee_data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Henry"],
    "Department": ["Engineering", "Data", "Engineering", "Cloud", "Data", "Security", "Cloud", "Engineering"],
    "Experience": [5, 3, 7, 4, 2, 8, 6, 1],
    "Score": [88, 92, 79, 85, 67, 95, 90, 72],
    "Status": ["Active", "Active", "Inactive", "Active", "Inactive", "Active", "Active", "Inactive"],
    "Remote": [True, True, False, True, False, False, True, True]
}

# Create a DataFrame
df_employees = pd.DataFrame(employee_data)

# Save the DataFrame as a CSV file
df_employees.to_csv(f"{input_dir}/{input_file}", index=False)

print("employee_performance.csv has been created.")

# Read the employee performance CSV file
df_employees = pd.read_csv("../assets/Week06/Day03/Input/employee_performance.csv")

employee_performance.csv has been created.

### Practice 1 — Add a Fixed Value Column
#### Goal: Practice adding a new column with the same value for every row.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Add a new column called Company to df_employees.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Set the value to: "ABC Tech"

In [22]:
df_employees["Company"] = "ABC Tech"

df_employees

      Name   Department  Experience  Score    Status  Remote   Company
0    Alice  Engineering           5     88    Active    True  ABC Tech
1      Bob         Data           3     92    Active    True  ABC Tech
2  Charlie  Engineering           7     79  Inactive   False  ABC Tech
3    David        Cloud           4     85    Active    True  ABC Tech
4      Eva         Data           2     67  Inactive   False  ABC Tech
5    Frank     Security           8     95    Active   False  ABC Tech
6    Grace        Cloud           6     90    Active    True  ABC Tech
7    Henry  Engineering           1     72  Inactive    True  ABC Tech

### Practice 2 — Add a Calculated Column
#### Goal: Practice creating a new column from an existing numeric column.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Create a new column called Experience_Months to df_employees.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Calculate it from the Experience column.<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;Formula:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Experience_Months = Experience * 12

In [25]:
df_employees["Experience_Months"] = df_employees["Experience"]*12

df_employees

,Name,Department,Experience,Score,Status,Remote,Company,Experience_Months
0,Alice,Engineering,5,88,Active,True,ABC Tech,60
1,Bob,Data,3,92,Active,True,ABC Tech,36
2,Charlie,Engineering,7,79,Inactive,False,ABC Tech,84
3,David,Cloud,4,85,Active,True,ABC Tech,48
4,Eva,Data,2,67,Inactive,False,ABC Tech,24
5,Frank,Security,8,95,Active,False,ABC Tech,96
6,Grace,Cloud,6,90,Active,True,ABC Tech,72
7,Henry,Engineering,1,72,Inactive,True,ABC Tech,12

### Practice 3 — Add a Boolean Column
#### Goal: Practice creating a boolean column from a condition.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Create a new column called High_Performer.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Set it to True if:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Score >= 85<br>
&nbsp;&nbsp;&nbsp;&nbsp;Otherwise, it should be False.

In [28]:
df_employees["High_Performer"] = df_employees["Score"]>=85

df_employees

,Name,Department,Experience,Score,Status,Remote,Company,Experience_Months,High_Performer
0,Alice,Engineering,5,88,Active,True,ABC Tech,60,True
1,Bob,Data,3,92,Active,True,ABC Tech,36,True
2,Charlie,Engineering,7,79,Inactive,False,ABC Tech,84,False
3,David,Cloud,4,85,Active,True,ABC Tech,48,True
4,Eva,Data,2,67,Inactive,False,ABC Tech,24,False
5,Frank,Security,8,95,Active,False,ABC Tech,96,True
6,Grace,Cloud,6,90,Active,True,ABC Tech,72,True
7,Henry,Engineering,1,72,Inactive,True,ABC Tech,12,False

### Practice 4 — Add a Conditional Score Level Column
#### Goal: Practice creating a new column using conditional logic.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Create a new column called Score_Level.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Use the following rules:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Score >= 90: Excellent<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Score >= 80: Good<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Score >= 70: Average<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Score < 70: Needs Improvement

In [30]:
df_employees["Score_Level"] = "Needs Improvement"

df_employees.loc[ df_employees["Score"]>=70, "Score_Level" ] = "Average"
df_employees.loc[ df_employees["Score"]>=80, "Score_Level" ] = "Good"
df_employees.loc[ df_employees["Score"]>=90, "Score_Level" ] = "Excellent"

df_employees

,Name,Department,Experience,Score,Status,Remote,Company,Experience_Months,High_Performer,Score_Level
0,Alice,Engineering,5,88,Active,True,ABC Tech,60,True,Good
1,Bob,Data,3,92,Active,True,ABC Tech,36,True,Excellent
2,Charlie,Engineering,7,79,Inactive,False,ABC Tech,84,False,Average
3,David,Cloud,4,85,Active,True,ABC Tech,48,True,Good
4,Eva,Data,2,67,Inactive,False,ABC Tech,24,False,Needs Improvement
5,Frank,Security,8,95,Active,False,ABC Tech,96,True,Excellent
6,Grace,Cloud,6,90,Active,True,ABC Tech,72,True,Excellent
7,Henry,Engineering,1,72,Inactive,True,ABC Tech,12,False,Average

### Practice 5 — Add a Bonus Eligibility Column
#### Goal: Practice creating a new column using multiple conditions.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Create a new column called Bonus_Eligible.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Set it to True if:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Score >= 85<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;AND<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Status is Active<br>
&nbsp;&nbsp;&nbsp;&nbsp;Otherwise, it should be False.

In [34]:
df_employees["Bonus_Eligible"] = (df_employees["Score"]>=85) & (df_employees["Status"]=="Active")

df_employees

,Name,Department,Experience,Score,Status,Remote,Company,Experience_Months,High_Performer,Score_Level,Bonus_Eligible
0,Alice,Engineering,5,88,Active,True,ABC Tech,60,True,Good,True
1,Bob,Data,3,92,Active,True,ABC Tech,36,True,Excellent,True
2,Charlie,Engineering,7,79,Inactive,False,ABC Tech,84,False,Average,False
3,David,Cloud,4,85,Active,True,ABC Tech,48,True,Good,True
4,Eva,Data,2,67,Inactive,False,ABC Tech,24,False,Needs Improvement,False
5,Frank,Security,8,95,Active,False,ABC Tech,96,True,Excellent,True
6,Grace,Cloud,6,90,Active,True,ABC Tech,72,True,Excellent,True
7,Henry,Engineering,1,72,Inactive,True,ABC Tech,12,False,Average,False

### Practice 6 — Add a Text Label Column
#### Goal: Practice creating a new text column by combining existing columns.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Create a new column called Employee_Label.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Format:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Name - Department

In [35]:
df_employees["Employee_Label"] = df_employees["Name"] + " - " + df_employees["Department"]
df_employees

,Name,Department,Experience,Score,Status,Remote,Company,Experience_Months,High_Performer,Score_Level,Bonus_Eligible,Employee_Label
0,Alice,Engineering,5,88,Active,True,ABC Tech,60,True,Good,True,Alice - Engineering
1,Bob,Data,3,92,Active,True,ABC Tech,36,True,Excellent,True,Bob - Data
2,Charlie,Engineering,7,79,Inactive,False,ABC Tech,84,False,Average,False,Charlie - Engineering
3,David,Cloud,4,85,Active,True,ABC Tech,48,True,Good,True,David - Cloud
4,Eva,Data,2,67,Inactive,False,ABC Tech,24,False,Needs Improvement,False,Eva - Data
5,Frank,Security,8,95,Active,False,ABC Tech,96,True,Excellent,True,Frank - Security
6,Grace,Cloud,6,90,Active,True,ABC Tech,72,True,Excellent,True,Grace - Cloud
7,Henry,Engineering,1,72,Inactive,True,ABC Tech,12,False,Average,False,Henry - Engineering

### Practice 7 — Add a Column After Filtering
#### Goal: Practice adding a new column after filtering rows.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Filter employees whose Score is greater than or equal to 85.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Create a copy of the filtered DataFrame.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Add a new column called Review_Note.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Set the value to:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;High score review needed

In [38]:
# Keep the filtered DataFrame in high_score_employees
high_score_employees = df_employees[ df_employees["Score"] >= 85 ].copy()

# Then, add the new column.
high_score_employees["Review_Note"] = "High score review needed"

high_score_employees

,Name,Department,Experience,Score,Status,Remote,Company,Experience_Months,High_Performer,Score_Level,Bonus_Eligible,Employee_Label,Review_Note
0,Alice,Engineering,5,88,Active,True,ABC Tech,60,True,Good,True,Alice - Engineering,High score review needed
1,Bob,Data,3,92,Active,True,ABC Tech,36,True,Excellent,True,Bob - Data,High score review needed
3,David,Cloud,4,85,Active,True,ABC Tech,48,True,Good,True,David - Cloud,High score review needed
5,Frank,Security,8,95,Active,False,ABC Tech,96,True,Excellent,True,Frank - Security,High score review needed
6,Grace,Cloud,6,90,Active,True,ABC Tech,72,True,Excellent,True,Grace - Cloud,High score review needed

## Summary

Today, I practiced adding new columns to pandas DataFrames.

I created a sample employee performance dataset and used it to practice different ways of adding new columns.

I learned how to add a fixed value column, create calculated columns from existing numeric columns, and create boolean columns based on conditions.

I also practiced creating conditional columns using `.loc[]`, combining multiple conditions with `&`, and creating text-based label columns by combining existing string columns.

In addition, I learned why using `.copy()` is useful when adding new columns to a filtered DataFrame.

I also saved DataFrames with newly added columns as CSV files, including the full employee dataset with new columns and a filtered dataset of bonus eligible employees.

These concepts are important because adding new columns is a common step in data cleaning, feature engineering, reporting, and machine learning preparation workflows.