# **Objective:** 
- Be able to group data by specific columns using pandas `groupby()`, and calculate summary statistics such as mean, sum, count, maximum, and minimum for each group.

# Today's Key Concepts
* **`groupby()`**: Splitting the DataFrame into groups based on specified column values
* **`mean()`**: Calculating the average value for each group
* **`sum()`**: Calculating the total sum of values for each group
* **`count()`**: Counting the number of non-null values in each group
* **`size()`**: Counting the total number of rows in each group (including null values)
* **`min()`**: Finding the minimum value within each group
* **`max()`**: Finding the maximum value within each group
* **`agg()`**: Applying multiple different aggregation functions to groups simultaneously
* **`reset_index()`**: Converting the grouped index back into regular DataFrame columns
* **Groupby with Multiple Columns**: Grouping data hierarchically by two or more columns
* **`sort_values()` After Groupby**: Sorting the aggregated results in ascending or descending order
* **Saving Grouped Results**: Exporting the final aggregated DataFrame to an external file

## groupby()
- groupby() allows you to split data into groups based on specific criteria, and then perform summary calculations for each group.

--- 

### Core Syntax: The `groupby()` Formula

```python
df.groupby("group_column")["target_column"].aggregation_function()
``` 

--- 

### Example: Calculating Departmental Averages

&nbsp;&nbsp;&nbsp;&nbsp;Let's assume we have the following employee dataset:

| Name | Department | Experience | Score | Status |
| :--- | :--- | :---: | :---: | :--- |
| Alice | Engineering | 5 | 88 | Active |
| Bob | Data | 3 | 92 | Active |
| Charlie | Engineering | 7 | 79 | Inactive |
| David | Cloud | 4 | 85 | Active |
| Eva | Data | 2 | 67 | Inactive |
| Frank | Security | 8 | 95 | Active |

#### &nbsp;&nbsp;&nbsp;&nbsp;Grouping by Department and Finding the Mean Score
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If you want to view the **average score for each department**, you can group the data and calculate the mean like this:

```python
    # Group by Department and calculate the average of the Score column
    df_employees.groupby("Department")["Score"].mean()
```
#### &nbsp;&nbsp;&nbsp;&nbsp;Code Anatomy: Step-by-Step Execution

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Here is exactly how pandas evaluates the statement from left to right:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**`df_employees`** ➡️ The source **DataFrame** containing all raw data.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**`.groupby("Department")`** ➡️ **Groups rows** based on unique categories within the "Department" column.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**`["Score"]`** ➡️ **Selects the target column** to isolate the data we want to calculate.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**`.mean()`** ➡️ **Computes the average** for each isolated group.
<br>
### Output
&nbsp;&nbsp;&nbsp;&nbsp;Department<br>
&nbsp;&nbsp;&nbsp;&nbsp;Cloud&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;85.0<br>
&nbsp;&nbsp;&nbsp;&nbsp;Data&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;79.5<br>
&nbsp;&nbsp;&nbsp;&nbsp;Engineering&nbsp;&nbsp;&nbsp;&nbsp;83.5<br>
&nbsp;&nbsp;&nbsp;&nbsp;Security&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;95.0<br>
&nbsp;&nbsp;&nbsp;&nbsp;Name: Score, dtype: float64<br><br>
### Data Flow Mechanism
&nbsp;&nbsp;&nbsp;&nbsp;Group rows by the "Department" column<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;↓<br>
&nbsp;&nbsp;&nbsp;&nbsp;Select the "Score" column within each Department<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;↓<br>
&nbsp;&nbsp;&nbsp;&nbsp;Calculate and output the Mean Score per Department<br>

### Creating a csv file for practice

In [1]:
# Import modules
import os
import pandas as pd

# Create input and output folders
input_dir = "../assets/Week06/Day04/Input"
output_dir = "../assets/Week06/Day04/Output"

os.makedirs(input_dir, exist_ok=True)
os.makedirs(output_dir, exist_ok=True)

# Create sample employee performance data
employee_data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Henry"],
    "Department": ["Engineering", "Data", "Engineering", "Cloud", "Data", "Security", "Cloud", "Engineering"],
    "Experience": [5, 3, 7, 4, 2, 8, 6, 1],
    "Score": [88, 92, 79, 85, 67, 95, 90, 72],
    "Status": ["Active", "Active", "Inactive", "Active", "Inactive", "Active", "Active", "Inactive"],
    "Remote": [True, True, False, True, False, False, True, True]
}

# Create a DataFrame
df_employees = pd.DataFrame(employee_data)

# Save the DataFrame as a CSV file
df_employees.to_csv(f"{input_dir}/employee_performance.csv", index=False)

print("employee_performance.csv has been created.")

employee_performance.csv has been created.

### Loading the created csv file

In [2]:
# Read the employee performance CSV file
df_employees = pd.read_csv(f"{input_dir}/employee_performance.csv")

# Display the DataFrame
df_employees

      Name   Department  Experience  Score    Status  Remote
0    Alice  Engineering           5     88    Active    True
1      Bob         Data           3     92    Active    True
2  Charlie  Engineering           7     79  Inactive   False
3    David        Cloud           4     85    Active    True
4      Eva         Data           2     67  Inactive   False
5    Frank     Security           8     95    Active   False
6    Grace        Cloud           6     90    Active    True
7    Henry  Engineering           1     72  Inactive    True

## 01. Calculating the Average Score per Department

In [3]:
department_avg_score = df_employees.groupby("Department")["Score"].mean()

department_avg_score

Department
Cloud          87.500000
Data           79.500000
Engineering    79.666667
Security       95.000000
Name: Score, dtype: float64

### Converting Groupby Results into a DataFrame
- Since `groupby()` often turns the grouping column into an index, you can use `.reset_index()` to convert it back into a standard DataFrame.

```Python
.groupby("group_column")["target_column"].aggregation_function().reset_index( name="new_column_name" )

In [4]:
department_avg_score = df_employees.groupby("Department")["Score"].mean().reset_index( name="Mean" )

department_avg_score

    Department       Mean
0        Cloud  87.500000
1         Data  79.500000
2  Engineering  79.666667
3     Security  95.000000

## 02. Counting Employees by Department
- Use .size()

In [5]:
department_employee_count = df_employees.groupby("Department").size().reset_index(name="Employee_count")

department_employee_count

    Department  Employee_count
0        Cloud               2
1         Data               2
2  Engineering               3
3     Security               1

## 03. Getting the Highest and Lowest Scores Together
- Use .max()

In [6]:
department_max_score = df_employees.groupby("Department")["Score"].max().reset_index( name="Max score")

department_max_score

    Department  Max score
0        Cloud         90
1         Data         92
2  Engineering         88
3     Security         95

In [7]:
department_min_score = df_employees.groupby("Department")["Score"].min().reset_index( name="Min score" )

department_min_score

    Department  Min score
0        Cloud         85
1         Data         67
2  Engineering         72
3     Security         95

## 04. agg()
- Running Multiple Group Calculations at Once

---

### Syntax
1. Using a list => Target groups are in [] out of .agg()<br>
&nbsp;&nbsp;&nbsp;&nbsp;df_employees.groupby("Department")**["Score"]**.agg(<b>["mean", "max", "min"]</b>).reset_index()<br><br>
2. Using a dictionary => Target groups are in .agg() with dictionary form <br>
&nbsp;&nbsp;&nbsp;&nbsp;dept_summary = df_employees.groupby("Department").agg({<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"Score": "mean",<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"Experience": "sum"<br>
&nbsp;&nbsp;&nbsp;&nbsp;}).reset_index()

### 04-01: Using a list
- Running Multiple Group Calculations at Once

In [8]:
department_score_summary = df_employees.groupby("Department")["Score"].agg(["mean","max","min","count"]).reset_index()

department_score_summary

    Department       mean  max  min  count
0        Cloud  87.500000   90   85      2
1         Data  79.500000   92   67      2
2  Engineering  79.666667   88   72      3
3     Security  95.000000   95   95      1

### 04-02: Using a dictionary
- Applying .agg() to Multiple Columns (looks like multi-level)

In [9]:
department_summary = df_employees.groupby("Department").agg({
    "Score":["mean", "max", "min"],
    "Experience":["mean", "max"]
}).reset_index()

department_summary

    Department      Score         Experience
                     mean max min       mean max
0        Cloud  87.500000  90  85   5.000000   6
1         Data  79.500000  92  67   2.500000   3
2  Engineering  79.666667  88  72   4.333333   7
3     Security  95.000000  95  95   8.000000   8

- It also can be like this (not multi-level)<br>
&nbsp;&nbsp;&nbsp;&nbsp;df.**groupby**("<i>group_column</i>").**agg**(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;title1 = (<i>"target_column</i>", "<i>aggregation_function()</i>"),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;title2 = (<i>"target_column</i>", "<i>aggregation_function()</i>"),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;title3 = (<i>"target_column</i>", "<i>aggregation_function()</i>"),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;).reset_index()

In [10]:
# Create a clear grouped summary using named aggregation
department_summary = df_employees.groupby("Department").agg(
    Average_Score=("Score", "mean"),
    Max_Score=("Score", "max"),
    Min_Score=("Score", "min"),
    Employee_Count=("Name", "count"),
    Average_Experience=("Experience", "mean")
).reset_index()

department_summary

,Department,Average_Score,Max_Score,Min_Score,Employee_Count,Average_Experience
0,Cloud,87.500000,90,85,2,5.000000
1,Data,79.500000,92,67,2,2.500000
2,Engineering,79.666667,88,72,3,4.333333
3,Security,95.000000,95,95,1,8.000000

## 05. Sorting Groupby Results
- Use .sort_values

.**sort_values( by=**"<i>group_column</i>", **ascending=**<i>True/False</i> **)**

In [11]:
department_summary_sorted = department_summary.sort_values(
    by="Average_Score",
    ascending=False
).reset_index(drop=True)

department_summary_sorted

,Department,Average_Score,Max_Score,Min_Score,Employee_Count,Average_Experience
0,Security,95.000000,95,95,1,8.000000
1,Cloud,87.500000,90,85,2,5.000000
2,Engineering,79.666667,88,72,3,4.333333
3,Data,79.500000,92,67,2,2.500000

## 06. Multi-column Groupby
- .grouby( [column_list] )

In [12]:
department_status_summary = df_employees.groupby(["Department", "Status"]).size().reset_index(name="Employee_count")

department_status_summary

    Department    Status  Employee_count
0        Cloud    Active               2
1         Data    Active               1
2         Data  Inactive               1
3  Engineering    Active               1
4  Engineering  Inactive               2
5     Security    Active               1

## 07. Grouping by a Boolean Column

In [13]:
# Calculate average score by Remote status
remote_score_summary = df_employees.groupby("Remote")["Score"].mean().reset_index()

remote_score_summary

   Remote      Score
0   False  80.333333
1    True  85.400000

## 08. Saving groupby results

In [14]:
department_summary_sorted.to_csv(f"{output_dir}/department_score_summary.csv", index=False)

print("department_score_summary.csv has been saved.")

department_score_summary.csv has been saved.

In [15]:
# Save a simple groupby summary as a text file
with open("../assets/Week06/Day04/Output/groupby_summary.txt", "w", encoding="utf-8") as file:
    file.write("GroupBy Summary\n")
    file.write("================\n")
    file.write(f"Total employees: {len(df_employees)}\n")
    file.write(f"Number of departments: {df_employees['Department'].nunique()}\n")
    file.write(f"Overall average score: {df_employees['Score'].mean():.2f}\n")
    file.write("\nTop department by average score:\n")
    file.write(f"{department_summary_sorted.iloc[0]['Department']}: {department_summary_sorted.iloc[0]['Average_Score']:.2f}\n")

print("groupby_summary.txt has been saved.")

groupby_summary.txt has been saved.

## Practice Problems

### Practice 1 — Average Score by Department
#### Goal: Practice grouping data by one column and calculating the average.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Group the DataFrame by Department.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Calculate the average Score for each department.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Store the result in department_avg_score.

In [16]:
department_avg_score = df_employees.groupby("Department")["Score"].mean().reset_index()

department_avg_score

    Department      Score
0        Cloud  87.500000
1         Data  79.500000
2  Engineering  79.666667
3     Security  95.000000

### Practice 2 — Count Employees by Department
#### Goal: Practice counting rows by group.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Count how many employees are in each department.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Store the result in department_employee_count.

In [17]:
department_employee_count = df_employees.groupby("Department").size().reset_index( name="Count")

department_employee_count

    Department  Count
0        Cloud      2
1         Data      2
2  Engineering      3
3     Security      1

### Practice 3 — Summary Statistics by Department
#### Goal: Practice calculating multiple statistics using agg().
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Group by Department.<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;For Score, calculate:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mean<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;max<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;min<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;count<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;Store the result in department_score_summary.

In [79]:
department_score_summary = df_employees.groupby("Department")["Score"].agg(["mean", "max", "min", "count"]).reset_index()
department_score_summary

    Department       mean  max  min  count
0        Cloud  87.500000   90   85      2
1         Data  79.500000   92   67      2
2  Engineering  79.666667   88   72      3
3     Security  95.000000   95   95      1

### Practice 4 — Named Aggregation
#### Goal: Practice creating a clean grouped summary with named aggregation.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Group by Department.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Create the following summary columns:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Average_Score<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Max_Score<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Min_Score<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Employee_Count<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Average_Experience

In [18]:
department_summary = df_employees.groupby("Department").agg(
    Average_Score = ("Score", "mean"),
    Max_Score = ("Score", "max"),
    Min_Score = ("Score", "min"),
    Employee_Count = ("Name", "count"),
    Average_Experience = ("Experience", "mean")
).reset_index()

department_summary

,Department,Average_Score,Max_Score,Min_Score,Employee_Count,Average_Experience
0,Cloud,87.500000,90,85,2,5.000000
1,Data,79.500000,92,67,2,2.500000
2,Engineering,79.666667,88,72,3,4.333333
3,Security,95.000000,95,95,1,8.000000

In [27]:
department_summary2 = df_employees.groupby("Department").agg(
    {
        "Score":["mean","max","min"],
        "Name":["count"],
        "Experience":["mean"]
    }
).reset_index()

department_summary2

    Department      Score          Name Experience
                     mean max min count       mean
0        Cloud  87.500000  90  85     2   5.000000
1         Data  79.500000  92  67     2   2.500000
2  Engineering  79.666667  88  72     3   4.333333
3     Security  95.000000  95  95     1   8.000000

### Practice 5 — Sort GroupBy Result
#### Goal: Practice sorting grouped summary results.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Sort department_summary by Average_Score in descending order.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Store the result in department_summary_sorted.<br>

In [30]:
department_summary_sorted = department_summary.sort_values(by="Average_Score", ascending=False).reset_index(drop=True)
department_summary_sorted

,Department,Average_Score,Max_Score,Min_Score,Employee_Count,Average_Experience
0,Security,95.000000,95,95,1,8.000000
1,Cloud,87.500000,90,85,2,5.000000
2,Engineering,79.666667,88,72,3,4.333333
3,Data,79.500000,92,67,2,2.500000

### Practice 6 — Group by Multiple Columns
#### Goal: Practice grouping by more than one column.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Group by:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Department<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Status<br>
&nbsp;&nbsp;&nbsp;&nbsp;Count employees in each group.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Store the result in department_status_summary.

In [39]:
department_status_summary = df_employees.groupby(["Department", "Status"]).size().reset_index(name="Employee_Count")
department_status_summary

    Department    Status  Employee_Count
0        Cloud    Active               2
1         Data    Active               1
2         Data  Inactive               1
3  Engineering    Active               1
4  Engineering  Inactive               2
5     Security    Active               1

### Practice 7 — Group by Boolean Column
#### Goal: Practice grouping by a boolean column.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Group by Remote.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Calculate the average Score.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Store the result in remote_score_summary.

In [40]:
remote_score_summary = df_employees.groupby("Remote")["Score"].mean().reset_index()

remote_score_summary

   Remote      Score
0   False  80.333333
1    True  85.400000

### Practice 8 — Save GroupBy Results
#### Goal: Practice saving grouped results as output files.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Save department_summary_sorted as:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;../assets/Week06/Day04/Output/department_score_summary.csv<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;Save department_status_summary as:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;../assets/Week06/Day04/Output/department_status_summary.csv

In [44]:
department_summary_sorted.to_csv(f"{output_dir}/department_score_summary_practice.csv", index=False)

if os.path.exists(f"{output_dir}/department_score_summary_practice.csv"):
    print("department_score_summary_practice.csv has been created.")

department_status_summary.to_csv(f"{output_dir}/department_status_summary_practice.csv", index=False)

if os.path.exists(f"{output_dir}/department_status_summary_practice.csv"):
    print("department_status_summary_practice.csv has been created.")

department_score_summary_practice.csv has been created.
department_status_summary_practice.csv has been created.

## Summary

Today, I practiced using `groupby()` in pandas.

I created a sample employee performance dataset and saved it as a CSV file. Then, I loaded the CSV file back into a pandas DataFrame for groupby practice.

I learned how to group data by one column and calculate summary statistics such as average, maximum, minimum, and count.

I practiced using `size()` to count rows by group and `agg()` to calculate multiple statistics at once.

I also practiced different ways to use `agg()`, including list-based aggregation, dictionary-based aggregation, and named aggregation for cleaner summary column names.

In addition, I grouped data by multiple columns, grouped data by a boolean column, sorted grouped results using `sort_values()`, and saved grouped summary results as CSV files.

I also saved a simple groupby summary as a `.txt` file.

These concepts are important because `groupby()` is one of the most common tools for summarizing, analyzing, and reporting structured data.