## Objective
- Be able to use pandas sort_values() to sort a DataFrame in ascending or descending order based on specific columns.

### Today's Key Concepts
- sort_values(): The core method used to sort a DataFrame by its values
- ascending=True: Sorting data in ascending order (lowest to highest, default)
- ascending=False: Sorting data in descending order (highest to lowest)
- Sorting by One Column: Sorting the entire DataFrame based on a single column's values
- Sorting by Multiple Columns: Sorting by multiple columns sequentially using a list (e.g., secondary sorting)
- reset_index(): Resetting the row index labels after sorting rearranges them
- inplace: Applying changes directly to the original DataFrame without creating a copy
- Saving Sorted Results: Assigning the sorted DataFrame back to a variable to persist the changes

## 01. sort_values()
- `sort_values()` is used to sort a DataFrame based on the values of a specific column.
- `sort_values()` returns a new DataFrame by default. `inplace=True` can be used to change the original DataFrame.

---

### Example: Student Score Dataset
Let's assume we have the following student dataset:

| Name | Age | Score | Department |
| :--- | :---: | :---: | :--- |
| Alice | 25 | 88 | Data |
| Bob | 30 | 92 | Engineering |
| Charlie | 35 | 79 | Data |
| David | 28 | 85 | Cloud |
| Eva | 22 | 67 | Engineering |
| Frank | 40 | 95 | Security |

#### 1) Sorting by Scores in Descending Order (Highest to Lowest)
&nbsp;&nbsp;&nbsp;&nbsp;If you want to view the students ranked from the highest score to the lowest, set `ascending=False`:
```python
df.sort_values(by="column", ascending=False)
```
#### 2) Sorting by Scores in Ascending Order (Lowest to Highest)
&nbsp;&nbsp;&nbsp;&nbsp;If you want to view the students ranked from the lowest score to the highest, set ascending=True (or omit it, as it is the default):
```Python
df.sort_values(by="column", ascending=True)
```

### Creating dataset to practice

In [7]:
# Import modules
import os
import pandas as pd

# Basic environment settings
# Input
input_dir = "../assets/Week06/Day01/Input/"
os.makedirs(input_dir, exist_ok=True)

input_file = "students.csv"
input_file_path = f"{input_dir}{input_file}"


# Output
output_dir = "../assets/Week06/Day01/Output/"
os.makedirs(output_dir, exist_ok=True)



# Create sample student data
student_data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank"],
    "Age": [25, 30, 35, 28, 22, 40],
    "Score": [88, 92, 79, 85, 67, 95],
    "Department": ["Data", "Engineering", "Data", "Cloud", "Engineering", "Security"],
    "Passed": [True, True, False, True, False, True]
}

# Creating a DataFrame
df_students = pd.DataFrame(student_data)

# Creating a CSV file
df_students.to_csv(input_file_path, index=False)

print("students.csv has been created.")

students.csv has been created.

In [50]:
# Read the student CSV file
df_students = pd.read_csv(input_file_path)
print(df_students)

      Name  Age  Score   Department  Passed
0    Alice   25     88         Data    True
1      Bob   30     92  Engineering    True
2  Charlie   35     79         Data   False
3    David   28     85        Cloud    True
4      Eva   22     67  Engineering   False
5    Frank   40     95     Security    True

### Sorting in ascending numerical order

In [10]:
asc_students = df_students.sort_values( by="Score", ascending=True )
asc_students

      Name  Age  Score   Department  Passed
4      Eva   22     67  Engineering   False
2  Charlie   35     79         Data   False
3    David   28     85        Cloud    True
0    Alice   25     88         Data    True
1      Bob   30     92  Engineering    True
5    Frank   40     95     Security    True

###  Sorting in descending numerical order

In [11]:
desc_students = df_students.sort_values( by="Score", ascending=False )
desc_students

      Name  Age  Score   Department  Passed
5    Frank   40     95     Security    True
1      Bob   30     92  Engineering    True
0    Alice   25     88         Data    True
3    David   28     85        Cloud    True
2  Charlie   35     79         Data   False
4      Eva   22     67  Engineering   False

### Sorting in ascending alphabetical order

In [13]:
asc_name_sorted = df_students.sort_values( by="Name", ascending=True )
asc_name_sorted

      Name  Age  Score   Department  Passed
0    Alice   25     88         Data    True
1      Bob   30     92  Engineering    True
2  Charlie   35     79         Data   False
3    David   28     85        Cloud    True
4      Eva   22     67  Engineering   False
5    Frank   40     95     Security    True

### Sorting in descending alphabetical order

In [15]:
desc_name_sorted = df_students.sort_values( by="Name", ascending=False )
desc_name_sorted

      Name  Age  Score   Department  Passed
5    Frank   40     95     Security    True
4      Eva   22     67  Engineering   False
3    David   28     85        Cloud    True
2  Charlie   35     79         Data   False
1      Bob   30     92  Engineering    True
0    Alice   25     88         Data    True

### Sorting by Multiple Columns
- To sort a DataFrame by multiple columns, pass a list of column names to the by parameter. The DataFrame will be sorted sequentially based on the order of the columns in the list.

In [17]:
df_multi_sort = df_students.sort_values( by=["Department", "Score"], ascending=True )
df_multi_sort

      Name  Age  Score   Department  Passed
3    David   28     85        Cloud    True
2  Charlie   35     79         Data   False
0    Alice   25     88         Data    True
4      Eva   22     67  Engineering   False
1      Bob   30     92  Engineering    True
5    Frank   40     95     Security    True

- `ascending=` can also have a list

In [18]:
df_multi_sort = df_students.sort_values( by=["Department", "Score"], ascending=[True, False] )
df_multi_sort

      Name  Age  Score   Department  Passed
3    David   28     85        Cloud    True
0    Alice   25     88         Data    True
2  Charlie   35     79         Data   False
1      Bob   30     92  Engineering    True
4      Eva   22     67  Engineering   False
5    Frank   40     95     Security    True

## 02. Resetting the Index After Sorting
- Sorting data via sort_values() rearranges the rows, but keeps the old index unchanged. If you want to refresh the index so it goes in order from 0, 1, 2..., use `reset_index()`.
- By default, the old index gets added as a new column on the far left. If you want to prevent this and completely remove the old index, simply set `drop=True` inside the function.

In [22]:
# By default, the old index gets added as a new column
sorted_df = df_students.sort_values(by="Score", ascending=False).reset_index()
sorted_df

   index     Name  Age  Score   Department  Passed
0      5    Frank   40     95     Security    True
1      1      Bob   30     92  Engineering    True
2      0    Alice   25     88         Data    True
3      3    David   28     85        Cloud    True
4      2  Charlie   35     79         Data   False
5      4      Eva   22     67  Engineering   False

In [23]:
# Using drop=True to remove the old index
df_drop_index = df_students.sort_values(by="Score", ascending=False).reset_index(drop=True)
df_drop_index

      Name  Age  Score   Department  Passed
0    Frank   40     95     Security    True
1      Bob   30     92  Engineering    True
2    Alice   25     88         Data    True
3    David   28     85        Cloud    True
4  Charlie   35     79         Data   False
5      Eva   22     67  Engineering   False

## 03. inplace=True
- `inplace=True` modifies the original DataFrame directly without creating a new copy. When this parameter is set, the method updates the existing object and returns `None`.
``` Python
    df_students.sort_values(by="Score", ascending=False, inplace=True)
```

## 04. Save the result to a csv file

In [54]:
df_sorted_by_score = df_students.sort_values( by="Score", ascending=False ).reset_index( drop=True )
df_sorted_by_score.to_csv(f"{output_dir}students_sorted_by_score.csv", index=False)

print("Sorted result has been saved.")

Sorted result has been saved.

## Practice Problems

### Practice 1 — Create a Sample CSV File
#### Goal: Practice creating a CSV file for sorting practice.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Create a DataFrame with the following columns:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Name<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Age<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Score<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Department<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Passed<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;Use at least six rows of data.<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;Save it as:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;../assets/Week06/Day01/Input/students.csv

In [28]:
input_data = "../assets/Week06/Day01/Input/students.csv"

student_data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank"],
    "Age": [25, 30, 35, 28, 22, 40],
    "Score": [88, 92, 79, 85, 67, 95],
    "Department": ["Data", "Engineering", "Data", "Cloud", "Engineering", "Security"],
    "Passed": [True, True, False, True, False, True]
}

pr_df_students = pd.DataFrame(student_data)

pr_df_students.to_csv(input_data, index=False)

if os.path.exists(input_data):
    print("File has been created")
else:
    print("Error occurred")

File has been created

### Practice 2 — Read the CSV File
#### Goal: Practice reading a CSV file before sorting data.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Read the following CSV file:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;../assets/Week06/Day01/Input/students.csv<br>
&nbsp;&nbsp;&nbsp;&nbsp;Store it in a variable called df_students.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Display the DataFrame.

In [49]:
df_students = pd.read_csv(input_data)

print(df_students)

      Name  Age  Score   Department  Passed
0    Alice   25     88         Data    True
1      Bob   30     92  Engineering    True
2  Charlie   35     79         Data   False
3    David   28     85        Cloud    True
4      Eva   22     67  Engineering   False
5    Frank   40     95     Security    True

### Practice 3 — Sort by Score in Ascending Order
#### Goal: Practice sorting numeric data in ascending order.
##### <U>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Sort df_students by Score from lowest to highest.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Store the result in df_score_ascending.

In [32]:
df_score_ascending = df_students.sort_values( by="Score" )
df_score_ascending

      Name  Age  Score   Department  Passed
4      Eva   22     67  Engineering   False
2  Charlie   35     79         Data   False
3    David   28     85        Cloud    True
0    Alice   25     88         Data    True
1      Bob   30     92  Engineering    True
5    Frank   40     95     Security    True

### Practice 4 — Sort by Score in Descending Order
#### Goal: Practice sorting numeric data in descending order.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Sort df_students by Score from highest to lowest.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Store the result in df_score_descending.

In [33]:
df_score_descending = df_students.sort_values( by="Score", ascending=False )
df_score_descending

      Name  Age  Score   Department  Passed
5    Frank   40     95     Security    True
1      Bob   30     92  Engineering    True
0    Alice   25     88         Data    True
3    David   28     85        Cloud    True
2  Charlie   35     79         Data   False
4      Eva   22     67  Engineering   False

### Practice 5 — Sort by Name
#### Goal: Practice sorting text data.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Sort df_students by Name in alphabetical order.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Store the result in df_name_sorted.

In [34]:
df_name_sorted = df_students.sort_values( by="Name", ascending=True )
df_name_sorted

      Name  Age  Score   Department  Passed
0    Alice   25     88         Data    True
1      Bob   30     92  Engineering    True
2  Charlie   35     79         Data   False
3    David   28     85        Cloud    True
4      Eva   22     67  Engineering   False
5    Frank   40     95     Security    True

### Practice 6 — Sort by Multiple Columns
#### Goal: Practice sorting by more than one column.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Sort df_students by:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Department in ascending order<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Score in descending order<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;Store the result in df_multi_sorted.

In [36]:
df_multi_sorted = df_students.sort_values( by=["Department", "Score"], ascending=[True, False] )
df_multi_sorted

      Name  Age  Score   Department  Passed
3    David   28     85        Cloud    True
0    Alice   25     88         Data    True
2  Charlie   35     79         Data   False
1      Bob   30     92  Engineering    True
4      Eva   22     67  Engineering   False
5    Frank   40     95     Security    True

### Practice 7 — Reset Index After Sorting
#### Goal: Practice resetting the index after sorting.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Sort df_students by Score in descending order.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Reset the index using reset_index(drop=True).<br>
&nbsp;&nbsp;&nbsp;&nbsp;Store the result in df_sorted_reset.

In [39]:
df_sorted_reset = df_students.sort_values( by="Score", ascending=False ).reset_index( drop=True)
df_sorted_reset

      Name  Age  Score   Department  Passed
0    Frank   40     95     Security    True
1      Bob   30     92  Engineering    True
2    Alice   25     88         Data    True
3    David   28     85        Cloud    True
4  Charlie   35     79         Data   False
5      Eva   22     67  Engineering   False

### Practice 8 — Save Sorted Result as CSV
#### Goal: Practice saving a sorted DataFrame as a CSV file.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Save df_sorted_reset as:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;../assets/Week06/Day01/Output/students_sorted_by_score.csv

In [51]:
pr_output_file = f"students_sorted_by_score.csv"
df_sorted_reset.to_csv(f"{output_dir}{pr_output_file}", index=False)

if os.path.exists(f"{output_dir}{pr_output_file}"):
    print("File has been created.")
else:
    print("Error.")

File has been created.

### Practice 9 — Save Top Students
#### Goal: Practice selecting top rows after sorting and saving the result.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Select the top 3 students from df_sorted_reset.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Save the result as:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;../assets/Week06/Day01/Output/top_students.csv

In [53]:
pr_output_file = f"top_students.csv"

top_three_students = df_sorted_reset.head(3)

top_three_students.to_csv(f"{output_dir}{pr_output_file}", index=False)

if os.path.exists(f"{output_dir}{pr_output_file}"):
    print("File has been created.")
else:
    print("Error.")

File has been created.

## Summary

Today, I practiced sorting pandas DataFrames using `sort_values()`.

I learned how to sort data by one column in ascending and descending order. I also practiced sorting text columns and sorting by multiple columns using different sorting directions.

I learned that `sort_values()` does not change the original DataFrame unless `inplace=True` is used. I also practiced using `reset_index(drop=True)` to create a clean index after sorting.

Finally, I saved sorted DataFrames as CSV files.

These concepts are important because sorting helps organize data, identify top or bottom records, and prepare data for analysis, reporting, and machine learning workflows.