## Goal
- Selecting single or multiple columns within a pandas DataFrame for data subsetting.

### Today's Key Concepts
- df["column_name"]: Selecting a single column (returns a Series)
- df[["column1", "column2"]]: Selecting multiple columns (returns a DataFrame)
- Series: Understanding the 1D data structure in pandas
- DataFrame: Understanding the 2D data structure in pandas
- Checking Columns: Inspecting column names using df.columns
- Saving to Variables: Assigning a selected column to a new variable
- Basic Calculations: Performing arithmetic operations on selected columns

In [11]:
import pandas as pd

# Read the students CSV file
df_students = pd.read_csv("../assets/Week05/Day03/Input/students.csv")

# Display the DataFrame
df_students

   Unnamed: 0     Name  Age  Score
0           0    Alice   25     88
1           1      Bob   30     92
2           2  Charlie   35     79
3           3    David   28     85

---
## 01. Checking Column names

In [15]:
# Check column names
df_students.columns

Index(['Unnamed: 0', 'Name', 'Age', 'Score'], dtype='object')

In [16]:
# Convert column names to a list
list(df_students.columns)

['Unnamed: 0', 'Name', 'Age', 'Score']

## 02. Selecting a Single Column
- To select a single column, pass the column name as a string inside square brackets.<br>
&nbsp;&nbsp;&nbsp;&nbsp;df<b>[</b> <i>"column"</i> <b>]</b>

In [17]:
# Select one column
df_students["Name"]

0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object

- Selecting a single column returns a Series rather than a DataFrame.

In [18]:
# Check the type of one selected column
name_column = df_students["Name"]

print(type(name_column))

<class 'pandas.core.series.Series'>

---
## 02. Series
- In pandas, a Series represents a 1D (one-dimensional) data structure. Think of it as a single column pulled out from a DataFrame table.<br>

<table style="margin-left: 20px; text-align: left; border-collapse: collapse; width: auto;">
    <thead>
        <tr>
            <th style="padding: 10px 20px; border: 1px;">DataFrame</th>
            <th style="padding: 10px 20px; border: 1px;">Series</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td style="text-align:center; border: 1px;">table</td>
            <td style="text-align:center; border: 1px;">one column</td>
        </tr>
    </tbody>
</table>

In [19]:
df_students["Score"]

0    88
1    92
2    79
3    85
Name: Score, dtype: int64

In [22]:
print(type(df_students["Score"]))

<class 'pandas.core.series.Series'>

---
## 03. Selecting a Single Column as a DataFrame
- Use double square brackets.<br>
&nbsp;&nbsp;&nbsp;&nbsp;df <b>[[</b> "column"** <b>]]</b>

In [23]:
# Check the type
name_dataframe = df_students[["Name"]]

print(type(name_dataframe))

<class 'pandas.core.frame.DataFrame'>

- summary<br>
&nbsp;&nbsp;&nbsp;&nbsp;df_students["Name"]&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;# Series<br>
&nbsp;&nbsp;&nbsp;&nbsp;df_students[["Name"]]&nbsp;&nbsp;&nbsp;&nbsp;# DataFrame

---
## 04. Selecting multiple columns
- Use a list of columns<br>
&nbsp;&nbsp;&nbsp;&nbsp;df[ **[column1, column2, ...]** ]
&nbsp;&nbsp;-> The reason for double brackets is that the inner brackets represent a list of column names

In [24]:
# Select multiple columns
df_students[["Name", "Score"]]

      Name  Score
0    Alice     88
1      Bob     92
2  Charlie     79
3    David     85

---
## 05. Selecting a numeric column allows you to perform calculations.
- .mean()
- .max()
- .min()

In [27]:
# Select the Score column
scores = df_students["Score"]

# Calculate basic statistics from the Score column
print("Max score:", df_students["Score"].max())
print("Min score:", df_students["Score"].min())
print("Average score:", df_students["Score"].mean())

Max score: 92
Min score: 79
Average score: 86.0

---
## 06. Selecting non-existent columns results in a KeyError.

In [57]:
#df_students["score"]    #KeyError: 'score'

---
## Practice Problems

### Practice 1 — Load the Students CSV File
#### Goal: Practice loading a CSV file before selecting columns.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Read the following CSV file:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;../assets/Week05/Day03/Input/students.csv<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;Store it in a variable called df_students.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Display the DataFrame.<br>

In [48]:
import pandas as pd
import os

dir_path = "../assets/Week05/Day03/Input/"
file_name = "students.csv"
full_file_path = f"{dir_path}{file_name}"

if os.path.exists(dir_path):
    os.makedirs(dir_path, exist_ok=True)

if os.path.exists(full_file_path):
    df_students = pd.read_csv(full_file_path)
    print("Successfully loaded.")
else:
    print("File not exists.")

df_students

Successfully loaded.

   Unnamed: 0     Name  Age  Score
0           0    Alice   25     88
1           1      Bob   30     92
2           2  Charlie   35     79
3           3    David   28     85

### Practice 2 — Check Column Names
#### Goal: Practice checking available column names before selecting columns.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Print the column names of df_students.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Also convert the column names to a list.

In [38]:
print(df_students.columns)
print(f"Converting to a list: {list(df_students.columns)}")

Index(['Unnamed: 0', 'Name', 'Age', 'Score'], dtype='object')
Converting to a list: ['Unnamed: 0', 'Name', 'Age', 'Score']

### Practice 3 — Select One Column
#### Goal: Practice selecting a single column from a DataFrame.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Select the Name column from df_students.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Store it in a variable called name_column.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Print the result and check its type.<br>

In [42]:
name_column = df_students["Name"]
print(name_column)
print(type(name_column))

0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object
<class 'pandas.core.series.Series'>

### Practice 4 — Select One Column as a DataFrame
#### Goal: Understand the difference between selecting a column as a Series and as a DataFrame.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Select the Name column as a DataFrame.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Store it in a variable called name_dataframe.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Display the result and check its type.<br>

In [44]:
name_dataframe = df_students[["Name"]]
print(name_dataframe)
print(f"Type: {type(name_dataframe)}.")

      Name
0    Alice
1      Bob
2  Charlie
3    David
Type: <class 'pandas.core.frame.DataFrame'>.

### Practice 5 — Select Multiple Columns
#### Goal: Practice selecting multiple columns from a DataFrame.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Select the following columns:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Name<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Score<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;Store the result in a variable called df_name_score.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Display the result.

In [45]:
df_name_score = df_students[["Name", "Score"]]
df_name_score

      Name  Score
0    Alice     88
1      Bob     92
2  Charlie     79
3    David     85

### Practice 6 — Select Numeric Column and Calculate Average
#### Goal: Practice selecting a numeric column and calculating a simple statistic.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Select the Score column.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Calculate the average score.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Print the result in this format:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Average score: 86.00<br>

In [46]:
score_column = df_students["Score"]
print(f"Average score: {score_column.mean():.2f}")

Average score: 86.00

### Practice 7 — Calculate Max and Min from a Column
#### Goal: Practice using basic methods on a selected numeric column.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Using the Score column, calculate:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Maximum score<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Minimum score<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Average score

In [47]:
print(f"Maximum score: {score_column.max()}")
print(f"Minimum score: {score_column.min()}")
print(f"Average score: {score_column.mean()}")

Maximum score: 92
Minimum score: 79
Average score: 86.0

### Practice 8 — Load Model Results and Select Columns
#### Goal: Practice selecting columns from another CSV file.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Read the following CSV file:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;../assets/Week05/Day03/Input/model_results.csv<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;Select the following columns:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Model<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Accuracy<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;Store the result in df_model_accuracy.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Display the result.

In [53]:
import pandas as pd
import os

dir_path = "../assets/Week05/Day03/Input/"
file_name = "model_results.csv"
full_file_path = f"{dir_path}{file_name}"

if os.path.exists(dir_path):
    os.makedirs(dir_path, exist_ok=True)

if os.path.exists(full_file_path):
    df_models = pd.read_csv(full_file_path)
    print("Successfully loaded.")
else:
    print("File not exists.")

df_model_accuracy = df_models[["Model", "Accuracy"]]
print(df_model_accuracy)

Successfully loaded.
                 Model  Accuracy
0  Logistic Regression    0.8234
1        Decision Tree    0.7542
2        Random Forest    0.8615

### Practice 9 — Calculate Average Model Accuracy
#### Goal: Practice selecting a numeric column from a model results DataFrame.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Using df_models, select the Accuracy column and calculate the average accuracy.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Print the result as a percentage.

In [56]:
model_acc = df_models["Accuracy"]
print(f"Average accuracy: {model_acc.mean()*100:.2f}%")

Average accuracy: 81.30%

## Summary

Today, I practiced selecting columns from pandas DataFrames.

I loaded CSV files into DataFrames and checked available column names using `df.columns`. I also converted column names into a list to make them easier to inspect.

I practiced selecting a single column using `df["column_name"]` and learned that selecting one column returns a pandas Series.

I also practiced selecting a single column as a DataFrame using double brackets, such as `df[["Name"]]`, and selecting multiple columns using `df[["Name", "Score"]]`.

In addition, I selected numeric columns and calculated simple statistics such as average, maximum, and minimum values.

I also practiced selecting columns from another CSV file, `model_results.csv`, and calculated the average model accuracy.

These concepts are important because column selection is one of the most common operations in data analysis, machine learning, and data engineering workflows.