## Goal
- Be able to load a CSV file into a DataFrame using pandas' read_csv() and verify its basic structure.

### Key Points
&nbsp;&nbsp;&nbsp;&nbsp;CSV file<br>
&nbsp;&nbsp;&nbsp;&nbsp;pd.read_csv()<br>
&nbsp;&nbsp;&nbsp;&nbsp;file path<br>
&nbsp;&nbsp;&nbsp;&nbsp;head()<br>
&nbsp;&nbsp;&nbsp;&nbsp;shape<br>
&nbsp;&nbsp;&nbsp;&nbsp;columns<br>
&nbsp;&nbsp;&nbsp;&nbsp;dtypes<br>
&nbsp;&nbsp;&nbsp;&nbsp;info()<br>
&nbsp;&nbsp;&nbsp;&nbsp;to_csv()

## 01. CSV
- Comma-Separated Values

## 02. Loading a CSV file - read_csv()
- pd<b>.read_csv(</b>"<i>csv_file_path</i>"<b>)</b>

In [1]:
import pandas as pd

df_students_loaded = pd.read_csv("../assets/Week05/Day02/Input/students.csv")
df_students_loaded

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79

## 03. Creating a CSV file - to_csv()
- pd<b>.to_csv(</b><i>"csv_save_path"<i><b>)</b>

In [3]:
import pandas as pd
import os

# path and file
output_dir = "../assets/Week05/Day02/Output/"
output_file = "students.csv"
full_path = f"{output_dir}{output_file}"

# Create a folder for outputs
os.makedirs(output_dir, exist_ok=True)

# Create sample student data
student_data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [25, 30, 35, 28],
    "Score": [88, 92, 79, 85]
}

# Create a DataFrame
df_students = pd.DataFrame(student_data)

# Store the DataFrame as a CSV file
# Setting "index=False" excludes the row index when saving the DataFrame to a CSV.
df_students.to_csv(full_path, index=False)

if os.path.exists(full_path):
    print("students.csv has been created.")
else:
    print("Error - file not created.")

students.csv has been created.

## 04. Reading and Inspecting a CSV File

| Method | Attribute Meaning |
| --- | --- |
| head() | Shows the first 5 rows by default|
| shape | Shows number of rows and columns |
| columns | Shows column names |
| dtypes | Shows data types of each column |
| info() | Shows summary information about the DataFrame |

In [4]:
df_students_loaded.head(2)

    Name  Age  Score
0  Alice   25     88
1    Bob   30     92

In [5]:
# Check the number of rows and columns
df_students_loaded.shape

(3, 3)

In [6]:
# Check column names
df_students_loaded.columns

Index(['Name', 'Age', 'Score'], dtype='object')

In [7]:
# Check data types
df_students_loaded.dtypes

Name     object
Age       int64
Score     int64
dtype: object

In [8]:
# Display DataFrame information
df_students_loaded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Score   3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

## 05. Frequently used options
- sep
- usecols
- nrows

### `sep`: By default, CSV files use a comma (,) separator, so setting sep="," is optional. However, if a file is delimited by other characters like ; or |, you can easily handle it by setting the `sep` option to the corresponding character.

- pd.read_csv("<i>path/file.csv</i>", **sep="**,**"**)

### `usecols`: Used when you want only to read specific columns

In [9]:
df_selected = pd.read_csv(
    "../assets/Week05/Day02/Input/students.csv",
    usecols=["Name", "Score"]
)

df_selected

      Name  Score
0    Alice     88
1      Bob     92
2  Charlie     79

### `nrows`: Used when you only want to read the first few rows of a file.

In [10]:
# Read only the first 2 rows
df_sample = pd.read_csv(
    "../assets/Week05/Day02/Input/students.csv",
    nrows=2
)

df_sample

    Name  Age  Score
0  Alice   25     88
1    Bob   30     92

## Practice Problems

### Practice 1 — Create a Sample CSV File
#### Goal: Practice creating a small CSV file for pandas practice.
##### Requirements
Create a DataFrame with the following columns:<br>
&nbsp;&nbsp;&nbsp;&nbsp;Name<br>
&nbsp;&nbsp;&nbsp;&nbsp;Age<br>
&nbsp;&nbsp;&nbsp;&nbsp;Score<br><br>
Use at least four rows of data.<br>
Save the DataFrame as:<br>
&nbsp;&nbsp;&nbsp;&nbsp;../assets/Week05/Day02/Output/practice_students.csv

In [11]:
import os
import pandas as pd

# path and file
output_dir = "../assets/Week05/Day02/Output/"
output_file = "practice_students.csv"
full_path = f"{output_dir}{output_file}"


students = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [25, 30, 35, 28],
    "Score": [88, 92, 79, 85]
}

df_student = pd.DataFrame(students)

df_student.to_csv(full_path, index=False)

if os.path.exists(full_path):
    print(f"{output_file} has been created.")
else:
    print(f"Error - file not created.")

practice_students.csv has been created.

### Practice 2 — Read a CSV File
#### Goal: Practice reading a CSV file using pd.read_csv().
##### Requirements
Read the following file:<br>
&nbsp;&nbsp;&nbsp;&nbsp;../assets/Week05/Day02/Input/students.csv<br><br>
Store it in a variable called df_students_loaded.<br>
Display the DataFrame.<br>

In [12]:
input_dir = "../assets/Week05/Day02/input/"
input_file = "students.csv"
full_path = f"{output_dir}{output_file}"

loaded_csv = pd.read_csv(full_path)
loaded_csv

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   28     85

### Practice 3 — Inspect the Loaded DataFrame
#### Goal: Practice checking the basic structure of a loaded DataFrame.
##### Requirements
Using df_students_loaded, check:<br>
&nbsp;&nbsp;&nbsp;&nbsp;First 5 rows<br>
&nbsp;&nbsp;&nbsp;&nbsp;Shape<br>
&nbsp;&nbsp;&nbsp;&nbsp;Column names<br>
&nbsp;&nbsp;&nbsp;&nbsp;Data types<br>
&nbsp;&nbsp;&nbsp;&nbsp;Basic info

In [13]:
df_students_loaded.head()

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79

In [14]:
df_students_loaded.shape

(3, 3)

In [15]:
df_students_loaded.columns

Index(['Name', 'Age', 'Score'], dtype='object')

In [16]:
df_students_loaded.dtypes

Name     object
Age       int64
Score     int64
dtype: object

In [17]:
df_students_loaded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Score   3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

### Practice 4 — Check if the CSV File Exists
#### Goal: Practice checking the file path before reading a CSV file.
##### Requirements
Use os.path.exists() to check whether this file exists:<br>
&nbsp;&nbsp;&nbsp;&nbsp;../assets/Week05/Day02/Input/students.csv<br><br>
If the file exists, print:<br>
&nbsp;&nbsp;&nbsp;&nbsp;CSV file exists.<br><br>
Otherwise, print:<br>
&nbsp;&nbsp;&nbsp;&nbsp;CSV file does not exist.

In [18]:
import os
import pandas as pd

input_dir = "../assets/Week05/Day02/input/"
input_file = "students.csv"
full_path = f"{output_dir}{output_file}"

if os.path.exists(full_path):
    print("CSV file exists.")
else:
    print("CSV file does not exist.")

CSV file exists.

### Practice 5 — Read Selected Columns
#### Goal: Practice reading only selected columns from a CSV file.
##### Requirements
Read only the following columns from students.csv:<br>
&nbsp;&nbsp;&nbsp;&nbsp;Name<br>
&nbsp;&nbsp;&nbsp;&nbsp;Score<br><br>
Store the result in df_name_score.

In [19]:
input_dir = "../assets/Week05/Day02/input/"
input_file = "students.csv"
full_path = f"{output_dir}{output_file}"

loaded_student = pd.read_csv(full_path, usecols=["Name", "Score"])

loaded_student

      Name  Score
0    Alice     88
1      Bob     92
2  Charlie     79
3    David     85

### Practice 6 — Read Only a Few Rows
#### Goal: Practice reading only a small number of rows from a CSV file.
##### Requirements
Read only the first two rows from students.csv.<br>
Store the result in df_first_two_rows.

In [20]:
input_dir = "../assets/Week05/Day02/input/"
input_file = "students.csv"
full_path = f"{output_dir}{output_file}"

df_first_two_rows = pd.read_csv(full_path, nrows=2)
df_first_two_rows

    Name  Age  Score
0  Alice   25     88
1    Bob   30     92

### Practice 7 — Create and Read a Model Results CSV
#### Goal: Practice creating and reading another CSV file.
##### Requirements
Create a DataFrame with the following columns:<br>
&nbsp;&nbsp;&nbsp;&nbsp;Model<br>
&nbsp;&nbsp;&nbsp;&nbsp;Accuracy<br>
&nbsp;&nbsp;&nbsp;&nbsp;Status<br><br>
Use at least three rows of data.<br><br>
Save it as:<br>
&nbsp;&nbsp;&nbsp;&nbsp;../assets/Week05/Day02/Output/model_results.csv<br><br>
Then read the file back into a DataFrame.

In [21]:
output_dir = "../assets/Week05/Day02/Output/"
output_file = "model_results.csv"
full_path = f"{output_dir}{output_file}"

model_results = {
    "Model": ["Logistic Regression", "Decision Tree", "Random Forest"],
    "Accuracy": [0.8234, 0.7542, 0.8615],
    "Status": ["Good", "Needs Improvement", "Good"]
}

df_model_results = pd.DataFrame(model_results)

df_model_results.to_csv(full_path)

df_model_results

                 Model  Accuracy             Status
0  Logistic Regression    0.8234               Good
1        Decision Tree    0.7542  Needs Improvement
2        Random Forest    0.8615               Good

## Summary

Today, I practiced reading CSV files using pandas.

I learned that CSV files store tabular data as comma-separated values and can be loaded into pandas DataFrames using `pd.read_csv()`.

I practiced creating sample CSV files with `to_csv()` and reading them back with `read_csv()`. I also inspected loaded DataFrames using `head()`, `shape`, `columns`, `dtypes`, and `info()`.

In addition, I practiced checking whether a file exists before reading it, reading selected columns with `usecols`, and reading a limited number of rows with `nrows`.

These concepts are important because CSV files are one of the most common data formats used in data analysis, machine learning, and data engineering workflows.