In [58]:
# Checking if Pandas is installed
import pandas as pd

print(pd.__version__)

2.2.3

## 01. DataFrame
- 2D data structure

DataFrame<br>
&nbsp;&nbsp;&nbsp;&nbsp;= table<br>
&nbsp;&nbsp;&nbsp;&nbsp;= rows + columns<br>
&nbsp;&nbsp;&nbsp;&nbsp;= Excel sheet-like structure

e.g.)
|  | Name | Age | Role| 
|---|---|---|---|
|0|Alice|25|Data Analyst|
|1|Bob|30|Data Engineer|
|2|Charlie|35|ML Engineer|

&nbsp;&nbsp;&nbsp;&nbsp;- Rows    → 0, 1, 2<br>
&nbsp;&nbsp;&nbsp;&nbsp;- Columns → Name, Age, Role

### Creating a DataFrame with a dictionary
- dictionary key   → column name
- dictionary value → column values

<i><b>dict_var</b></i> = {<br>
&nbsp;&nbsp;&nbsp;&nbsp;<i>"Column_1": [ "row_1_1", "row_1_2", "row_1_3", ...],<br>
&nbsp;&nbsp;&nbsp;&nbsp;"Column_2": [ "row_2_1", "row_2_2", "row_2_3", ...],<br>
&nbsp;&nbsp;&nbsp;&nbsp;"Column_3": [ "row_3_1", "row_3_2", "row_3_3", ...],<br></i>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:<br>
}

pd.DataFrame( <i><b>dict_var</b></i> )

-->

|  | Column_1 | Column_2 | Column_3 | ... |
|---|---|---|---|---|
|0| row_1_1 | row_2_1 | row_3_1 | ... |
|1| row_1_2 | row_2_2 | row_3_2 | ... |
|2| row_1_3 | row_2_3 | row_3_3 | ... |

In [8]:
import pandas as pd

# Create a dictionary with column names as keys
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "Role": ["Data Analyst", "Data Engineer", "ML Engineer"]
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)

df

      Name  Age           Role
0    Alice   25   Data Analyst
1      Bob   30  Data Engineer
2  Charlie   35    ML Engineer

### Creating a DataFrame with a list of dictionaries
- This approach is commonly used when converting JSON data or API responses into a DataFrame.

<i><b>dict_var</b></i> = [<br>
&nbsp;&nbsp;&nbsp;&nbsp;{ <i>"Column_1":"row_1_1", "Column_2":"row_2_1", "Column_3":"row_3_1"</i> },<br>
&nbsp;&nbsp;&nbsp;&nbsp;{ <i>"Column_1":"row_1_2", "Column_2":"row_2_2", "Column_3":"row_3_2"</i> },<br>
&nbsp;&nbsp;&nbsp;&nbsp;{ <i>"Column_1":"row_1_3", "Column_2":"row_2_3", "Column_3":"row_3_3"</i> },<br></i>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;}
]

pd.DataFrame( <i><b>dict_var</b></i> )

-->

|  | Colum_1 | Colum_2 | Colum_3 | ... |
|---|---|---|---|---|
|0| row_1_1 | row_2_1 | row_3_1 | ... |
|1| row_1_2 | row_2_2 | row_3_2 | ... |
|2| row_1_3 | row_2_3 | row_3_3 | ... |

In [9]:
import pandas as pd

# Create a list of dictionaries
students = [
    {"Name": "Alice", "Age": 25, "Score": 88},
    {"Name": "Bob", "Age": 30, "Score": 92},
    {"Name": "Charlie", "Age": 35, "Score": 79}
]

# Create a DataFrame from the list of dictionaries
df_students = pd.DataFrame(students)

df_students

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79

## 02. Custom index
- Default index: 0, 1, 2, 3, ...
- but custom indexes can be set

<i>var</i> = pd.DataFrame( data, <b>index</b>=[ <i>"index_1", "index_2", ... </i> ] )

In [11]:
import pandas as pd

# Create sample data
data = {
    "Skill": ["Python", "SQL", "Pandas"],
    "Level": ["Beginner", "Intermediate", "Beginner"]
}

# Create a DataFrame with custom index labels
df_skills = pd.DataFrame(data, index=["A", "B", "C"])

df_skills

    Skill         Level
A  Python      Beginner
B     SQL  Intermediate
C  Pandas      Beginner

## 03. Basic methods
- **head()**: Display the first 5 rows as default
- **shape**: Check the number of rows and columns
- **columns**: Check column names
- **dtypes**: Check data types
- **infor()**: Display basic information about the DataFrame

In [17]:
df.head()

      Name  Age           Role
0    Alice   25   Data Analyst
1      Bob   30  Data Engineer
2  Charlie   35    ML Engineer

In [24]:
print(f"Shape: {df.shape}")
print(f"Column names: {df.columns}")
print(f"Data Types: \n{df.dtypes}")

Shape: (3, 3)
Column names: Index(['Name', 'Age', 'Role'], dtype='object')
Data Types:
Name    object
Age      int64
Role    object
dtype: object

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Role    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

## Practice Problems

### Practice 1 — Check pandas Installation
#### Goal: Practice importing pandas and checking the installed version.
##### Requirements
- Import pandas using the alias pd.
- Print the pandas version.

In [28]:
import pandas as pd

print(pd.__version__)

2.2.3

### Practice 2 — Create a Simple DataFrame
#### Goal: Practice creating a DataFrame from a dictionary.
##### Requirements
Create a DataFrame with the following columns:<br>
&nbsp;&nbsp;&nbsp;&nbsp;Name<br>
&nbsp;&nbsp;&nbsp;&nbsp;Age<br>
&nbsp;&nbsp;&nbsp;&nbsp;Role<br>
Use at least three rows of data.<br>

In [30]:
import pandas as pd

person = {
    "Name": ["Per", "Sons", "Name"],
    "Age": [15, 32, 24],
    "Role": ["Streamer", "Cook", "Software engineer"]
}

df_person = pd.DataFrame(person)
df_person

   Name  Age               Role
0   Per   15           Streamer
1  Sons   32               Cook
2  Name   24  Software engineer

### Practice 3 — Create a DataFrame from a List of Dictionaries
#### Goal: Practice creating a DataFrame from a list of dictionaries.
##### Requirements
Create a list of dictionaries containing model results.<br><br>
Each dictionary should include:<br>
&nbsp;&nbsp;&nbsp;&nbsp;Model<br>
&nbsp;&nbsp;&nbsp;&nbsp;Accuracy<br>
&nbsp;&nbsp;&nbsp;&nbsp;Status<br><br>
Then convert it into a DataFrame.

In [33]:
import pandas as pd

list_dict = [
    {"Model": "Logistic Regression", "Accuracy": 0.8234, "Status": "Good"},
    {"Model": "Decision Tree", "Accuracy": 0.7542, "Status": "Needs Improvement"},
    {"Model": "Random Forest", "Accuracy": 0.8615, "Status": "Good"}
]

df_model = pd.DataFrame(list_dict)
df_model

                 Model  Accuracy             Status
0  Logistic Regression    0.8234               Good
1        Decision Tree    0.7542  Needs Improvement
2        Random Forest    0.8615               Good

### Practice 4 — Create a DataFrame with a Custom Index
#### Goal: Practice creating a DataFrame with custom index labels.
#### Requirements
Create a DataFrame with the following columns:<br>
&nbsp;&nbsp;&nbsp;&nbsp;Skill<br>
&nbsp;&nbsp;&nbsp;&nbsp;Category<br>
&nbsp;&nbsp;&nbsp;&nbsp;Current_Level<br><br>
Use custom index labels:<br>
&nbsp;&nbsp;&nbsp;&nbsp;A<br>
&nbsp;&nbsp;&nbsp;&nbsp;B<br>
&nbsp;&nbsp;&nbsp;&nbsp;C<br>
&nbsp;&nbsp;&nbsp;&nbsp;D

In [39]:
import pandas as pd

skills = {
    "Skill": ["Python", "C", "SQL", "AWS", "Pandas", "Scikit-learn", "Linux"],
    "Category": ["Programming", "Programming", "Database", "Cloud", "Data Analysis", "ML", "OS"],
    "Current_Level": ["Intermediate", "Intermediate", "Intermediate", "Beginner", "Beginner", "Beginner", "Intermediate"]
}

df_skills = pd.DataFrame(skills, index=["A", "B", "C", "D", "E", "F", "G"])
df_skills

          Skill       Category Current_Level
A        Python    Programming  Intermediate
B             C    Programming  Intermediate
C           SQL       Database  Intermediate
D           AWS          Cloud      Beginner
E        Pandas  Data Analysis      Beginner
F  Scikit-learn             ML      Beginner
G         Linux             OS  Intermediate

### Practice 5 — Inspect a DataFrame
#### Goal: Practice checking basic DataFrame information.
##### Requirements
Using one of the DataFrames created above, check:<br>
&nbsp;&nbsp;&nbsp;&nbsp;First 5 rows<br>
&nbsp;&nbsp;&nbsp;&nbsp;Shape<br>
&nbsp;&nbsp;&nbsp;&nbsp;Column names<br>
&nbsp;&nbsp;&nbsp;&nbsp;Data types<br>
&nbsp;&nbsp;&nbsp;&nbsp;Basic info

In [41]:
# First 5 rows
df_skills.head()

    Skill       Category Current_Level
A  Python    Programming  Intermediate
B       C    Programming  Intermediate
C     SQL       Database  Intermediate
D     AWS          Cloud      Beginner
E  Pandas  Data Analysis      Beginner

In [52]:
# Shape, Column names, Data type
print(f"df_skills' shape: {df_skills.shape}")
print(f"df_skills' Column Names: {df_skills.columns}")
print(f"df_skills' Data Type: {df_skills.dtypes}")

df_skills' shape: (7, 3)
df_skills' Column Names: Index(['Skill', 'Category', 'Current_Level'], dtype='object')
df_skills' Data Type: Skill            object
Category         object
Current_Level    object
dtype: object

In [56]:
# Information
df_skills.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, A to G
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Skill          7 non-null      object
 1   Category       7 non-null      object
 2   Current_Level  7 non-null      object
dtypes: object(3)
memory usage: 224.0+ bytes

### Practice 6 — Create an Employee DataFrame
#### Goal: Practice creating a DataFrame using work-related sample data.
##### Requirements
Create a DataFrame with the following columns:<br>
&nbsp;&nbsp;&nbsp;&nbsp;Employee_ID<br>
&nbsp;&nbsp;&nbsp;&nbsp;Department<br>
&nbsp;&nbsp;&nbsp;&nbsp;Role<br>
&nbsp;&nbsp;&nbsp;&nbsp;Years_Experience<br><br>
Use at least four rows of data.<br>
Then display the DataFrame.

In [57]:
employee_data = {
    "Employee_ID": [101, 102, 103, 104],
    "Department": ["Engineering", "Data", "Cloud", "Security"],
    "Role": ["Software Developer", "Data Engineer", "Cloud Engineer", "Security Analyst"],
    "Years_Experience": [5, 3, 2, 4]
}

df_employees = pd.DataFrame(employee_data)

df_employees

   Employee_ID   Department                Role  Years_Experience
0          101  Engineering  Software Developer                 5
1          102         Data       Data Engineer                 3
2          103        Cloud      Cloud Engineer                 2
3          104     Security    Security Analyst                 4

## Summary

Today, I started learning pandas and practiced creating basic DataFrames.

I first checked whether pandas was installed by importing it with `import pandas as pd` and printing the pandas version.

I learned that a DataFrame is a two-dimensional table-like data structure made of rows and columns. I practiced creating DataFrames from a dictionary and from a list of dictionaries.

I also practiced creating a DataFrame with custom index labels and inspected basic DataFrame information using `head()`, `shape`, `columns`, `dtypes`, and `info()`.

For practice, I created several simple DataFrames, including a basic person DataFrame, model result DataFrame, skill DataFrame, and employee DataFrame.

These concepts are important because DataFrames are one of the most commonly used data structures in data analysis, machine learning, and data engineering workflows.