## Required Features
1. Create or load a sample CSV file.
2. Read the CSV file using pandas.
3. Inspect the DataFrame using head(), shape, columns, dtypes, and info().
4. Select important columns.
5. Filter rows based on conditions.
6. Calculate simple statistics.
7. Save the analysis summary as a .txt file.
8. Save filtered DataFrames as .csv files.
9. Notebook includes explanation, code, output, and summary.

In [36]:
import os
import pandas as pd

# Create input and output folders
input_dir = "../assets/Week05/Weekend/Input/"
input_file = "students.csv"
input_full_path = f"{input_dir}{input_file}"

output_dir = "../assets/Week05/Weekend/Output/"
summary_file = f"{output_dir}/analysis_summary.txt"
high_score_file = f"{output_dir}/high_score_students.csv"
passed_students_file = f"{output_dir}/passed_students.csv"

os.makedirs(input_dir, exist_ok=True)
os.makedirs(output_dir, exist_ok=True)

In [10]:
# Create sample student data
student_data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank"],
    "Age": [25, 30, 35, 28, 22, 40],
    "Score": [88, 92, 79, 85, 67, 95],
    "Department": ["Data", "Engineering", "Data", "Cloud", "Engineering", "Security"],
    "Passed": [True, True, False, True, False, True]
}

# Create a DataFrame
df_students = pd.DataFrame(student_data)

# Save the DataFrame as a CSV file
df_students.to_csv(input_full_path, index=False)

print("students.csv has been created.")

students.csv has been created.

In [11]:
# Read the CSV file
df = pd.read_csv(input_full_path)

# Display the DataFrame
df

      Name  Age  Score   Department  Passed
0    Alice   25     88         Data    True
1      Bob   30     92  Engineering    True
2  Charlie   35     79         Data   False
3    David   28     85        Cloud    True
4      Eva   22     67  Engineering   False
5    Frank   40     95     Security    True

In [18]:
# Inspect the DataFrame
print("First 5 rows:")
print(df.head())

# Shape
print("\nShape:", df.shape)

# Columns
print("\nColumns:", list(df.columns))

# Data type
print("\nData type:")
print(df.dtypes)

First 5 rows:
      Name  Age  Score   Department  Passed
0    Alice   25     88         Data    True
1      Bob   30     92  Engineering    True
2  Charlie   35     79         Data   False
3    David   28     85        Cloud    True
4      Eva   22     67  Engineering   False

Shape: (6, 5)

Columns: ['Name', 'Age', 'Score', 'Department', 'Passed']

Data type:
Name          object
Age            int64
Score          int64
Department    object
Passed          bool
dtype: object

In [19]:
# Select important columns
df_name_score = df[ ["Name", "Score"] ]
df_name_score

      Name  Score
0    Alice     88
1      Bob     92
2  Charlie     79
3    David     85
4      Eva     67
5    Frank     95

In [20]:
# Filter high score students
high_score_students = df[ df["Score"]>=85 ]
high_score_students

    Name  Age  Score   Department  Passed
0  Alice   25     88         Data    True
1    Bob   30     92  Engineering    True
3  David   28     85        Cloud    True
5  Frank   40     95     Security    True

In [22]:
# Filter passed students
passed_students = df[ df["Passed"] ]
passed_students

    Name  Age  Score   Department  Passed
0  Alice   25     88         Data    True
1    Bob   30     92  Engineering    True
3  David   28     85        Cloud    True
5  Frank   40     95     Security    True

In [33]:
# Calculate simple statistics
# total, average, maximum, minimum, sum
total_students = len(df)
average_score = df["Score"].mean()
max_score = df["Score"].max()
min_score = df["Score"].min()
passed_count =  df["Passed"].sum()
passed_rate = df["Passed"].sum()/total_students*100

print(f"Total students: {total_students}")
print(f"Average score: {average_score:.2f}")
print(f"Max score: {max_score}")
print(f"Min score: {min_score}")
print(f"Passed count: {passed_count}")
print(f"Passed rate: {passed_rate:.2f}%")

Total students: 6
Average score: 84.33
Max score: 95
Min score: 67
Passed count: 4
Passed rate: 66.67%

In [35]:
# Save analysis summary to a text file
with open(summary_file, "w", encoding="utf-8") as file:
    file.write("Simple CSV Analysis Summary\n")
    file.write("===========================\n")
    file.write(f"Total students: {total_students}\n")
    file.write(f"Average score: {average_score:.2f}\n")
    file.write(f"Max score: {max_score}\n")
    file.write(f"Min score: {min_score}\n")
    file.write(f"Passed count: {passed_count}\n")
    file.write(f"Passed rate: {passed_rate:.2f}%\n")

print("Analysis summary has been saved.")

Analysis summary has been saved.

In [38]:
# Read the saved summary file to confirm the result
with open(summary_file, "r", encoding="utf-8") as file:
    saved_summary = file.read()

print(saved_summary)

Simple CSV Analysis Summary
===========================
Total students: 6
Average score: 84.33
Max score: 95
Min score: 67
Passed count: 4
Passed rate: 66.67%

In [39]:
# Save filtered DataFrames as CSV files
high_score_students.to_csv(high_score_file, index=False)
passed_students.to_csv(passed_students_file, index=False)

print("Filtered CSV files have been saved.")

Filtered CSV files have been saved.

## Summary

In this weekend practice, I created a simple CSV analysis project using pandas.

I created a sample student dataset, saved it as a CSV file, and loaded it back into a pandas DataFrame using `pd.read_csv()`.

I practiced inspecting the DataFrame with `head()`, `shape`, `columns`, and `dtypes`. I also selected important columns and filtered rows based on conditions such as high scores and passed students.

I calculated simple statistics, including total student count, average score, maximum score, minimum score, passed count, and passed rate.

Finally, I saved the analysis summary as a `.txt` file and saved filtered DataFrames as `.csv` files.

This practice helped me combine pandas basics into a small end-to-end CSV analysis workflow.