In [1]:
# Creating a data file
import os
import pandas as pd

input_dir = "../assets/Week07/Day01/Input"
output_dir = "../assets/Week07/Day01/output"

os.makedirs(input_dir, exist_ok=True)
os.makedirs(output_dir, exist_ok=True)

input_file_path = f"{input_dir}/employee_data_with_missing_values.csv"

employee_data = {
    "Employee_ID": [101, 102, 103, 104, 105, 106, 107, 108],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Henry"],
    "Department": ["Engineering", "Data", None, "Cloud", "Data", "Security", None, "Engineering"],
    "Experience": [5, 3, 7, None, 2, 8, 6, 1],
    "Score": [88, 92, None, 85, 67, 95, 90, None],
    "Status": ["Active", "Active", "Inactive", "Active", None, "Active", "Active", "Inactive"],
    "Remote": [True, True, False, True, None, False, True, True]
}

# Create a DataFrame
df_employees = pd.DataFrame(employee_data)

# Save the DataFrame as a CSV file
df_employees.to_csv(input_file_path, index=False)

print("employee_data_with_missing_values.csv has been created.")

employee_data_with_missing_values.csv has been created.

In [2]:
# Read the employee CSV file
df_employees = pd.read_csv(input_file_path)
    
# Display the DataFrame
df_employees

   Employee_ID     Name   Department  Experience  Score    Status Remote
0          101    Alice  Engineering         5.0   88.0    Active   True
1          102      Bob         Data         3.0   92.0    Active   True
2          103  Charlie          NaN         7.0    NaN  Inactive  False
3          104    David        Cloud         NaN   85.0    Active   True
4          105      Eva         Data         2.0   67.0       NaN    NaN
5          106    Frank     Security         8.0   95.0    Active  False
6          107    Grace          NaN         6.0   90.0    Active   True
7          108    Henry  Engineering         1.0    NaN  Inactive   True

## 01. Checking for Missing Values using isnull()

In [3]:
missing_value_table = df_employees.isnull()
missing_value_table

   Employee_ID   Name  Department  Experience  Score  Status  Remote
0        False  False       False       False  False   False   False
1        False  False       False       False  False   False   False
2        False  False        True       False   True   False   False
3        False  False       False        True  False   False   False
4        False  False       False       False  False    True    True
5        False  False       False       False  False   False   False
6        False  False        True       False  False   False   False
7        False  False       False       False   True   False   False

## 02. Counting missing values per column

In [7]:
# Count missing values in each column
missing_count_by_column = df_employees.isnull().sum()

missing_count_by_column

Employee_ID    0
Name           0
Department     2
Experience     1
Score          2
Status         1
Remote         1
dtype: int64

## 03. Total number of missing values across the entire DataFrame

In [8]:
# Count the total number of missing values
total_missing_count = df_employees.isnull().sum().sum()

print(f"Total missing values: {total_missing_count}")

Total missing values: 7

## 04. Calculating the percentage of missing values per column

In [14]:
# Calculate missing value percentages by column
missing_percentage_by_column = ( df_employees.isnull().mean() * 100 ).round(2)

missing_percentage_by_column

Employee_ID     0.0
Name            0.0
Department     25.0
Experience     12.5
Score          25.0
Status         12.5
Remote         12.5
dtype: float64

## 05. Filtering rows with at least one missing value

In [15]:
# Find rows that contain at least one missing value
rows_with_missing_values = df_employees[ df_employees.isnull().any(axis=1) ]

rows_with_missing_values

   Employee_ID     Name   Department  Experience  Score    Status Remote
2          103  Charlie          NaN         7.0    NaN  Inactive  False
3          104    David        Cloud         NaN   85.0    Active   True
4          105      Eva         Data         2.0   67.0       NaN    NaN
6          107    Grace          NaN         6.0   90.0    Active   True
7          108    Henry  Engineering         1.0    NaN  Inactive   True

## 06. Counting missing values per row

In [18]:
# Count missing values in each row
missing_count_by_row = df_employees.isnull().sum(axis=1)

missing_count_by_row

0    0
1    0
2    2
3    1
4    2
5    0
6    1
7    1
dtype: int64

In [20]:
# Create a temporary DataFrame with missing value counts
df_missing_count = df_employees.copy()

df_missing_count["Missing_Value_Count"] = df_missing_count.isnull().sum(axis=1)

df_missing_count

   Employee_ID     Name   Department  Experience  Score    Status Remote  Missing_Value_Count
0          101    Alice  Engineering         5.0   88.0    Active   True                    0
1          102      Bob         Data         3.0   92.0    Active   True                    0
2          103  Charlie          NaN         7.0    NaN  Inactive  False                    2
3          104    David        Cloud         NaN   85.0    Active   True                    1
4          105      Eva         Data         2.0   67.0       NaN    NaN                    2
5          106    Frank     Security         8.0   95.0    Active  False                    0
6          107    Grace          NaN         6.0   90.0    Active   True                    1
7          108    Henry  Engineering         1.0    NaN  Inactive   True                    1

## 07. Finding missing values in a specific column

In [21]:
# e.g.) Find employees with missing Score values
missing_score_rows = df_employees[ df_employees["Score"].isnull() ]

missing_score_rows

   Employee_ID     Name   Department  Experience  Score    Status Remote
2          103  Charlie          NaN         7.0    NaN  Inactive  False
7          108    Henry  Engineering         1.0    NaN  Inactive   True

In [22]:
# e.g.) Find employees with missing Department values
missing_department_rows = df_employees[ df_employees["Department"].isnull() ]

missing_department_rows

   Employee_ID     Name Department  Experience  Score    Status Remote
2          103  Charlie        NaN         7.0    NaN  Inactive  False
6          107    Grace        NaN         6.0   90.0    Active   True

## 08. Extracting rows with no missing values
- .notnull().all(axis=1)

In [25]:
complete_rows = df_employees[ df_employees.notnull().all(axis=1) ]

complete_rows

   Employee_ID   Name   Department  Experience  Score  Status Remote
0          101  Alice  Engineering         5.0   88.0  Active   True
1          102    Bob         Data         3.0   92.0  Active   True
5          106  Frank     Security         8.0   95.0  Active  False

## 09. Checking for the existence of any missing values

In [30]:
# Check whether the DataFrame contains any missing values
has_missing_values = df_employees.isnull().any().any()

print(f"Does the DataFrame contain missing values? {has_missing_values}")

Does the DataFrame contain missing values? True

## 10. Creating Missing Value Summary

In [35]:
# Create missing value counts
missing_count_by_column = df_employees.isnull().sum()

# Create missing value percentages
missing_percentage_by_column = (df_employees.isnull().mean() * 100).round(2)

# Create a missing value summary DataFrame
missing_value_summary = pd.DataFrame(
    {
        "Column":df_employees.columns,
        "Missing_Count":missing_count_by_column.values,
        "Missing_Percentage":missing_percentage_by_column.values
    }
)
missing_value_summary

        Column  Missing_Count  Missing_Percentage
0  Employee_ID              0                 0.0
1         Name              0                 0.0
2   Department              2                25.0
3   Experience              1                12.5
4        Score              2                25.0
5       Status              1                12.5
6       Remote              1                12.5

In [37]:
missing_value_summary_with_missing_only = missing_value_summary[ missing_value_summary["Missing_Count"] > 0 ]

missing_value_summary_with_missing_only

       Column  Missing_Count  Missing_Percentage
2  Department              2                25.0
3  Experience              1                12.5
4       Score              2                25.0
5      Status              1                12.5
6      Remote              1                12.5

## 11. Saving the summary

In [38]:
rows_with_missing_values

   Employee_ID     Name   Department  Experience  Score    Status Remote
2          103  Charlie          NaN         7.0    NaN  Inactive  False
3          104    David        Cloud         NaN   85.0    Active   True
4          105      Eva         Data         2.0   67.0       NaN    NaN
6          107    Grace          NaN         6.0   90.0    Active   True
7          108    Henry  Engineering         1.0    NaN  Inactive   True

In [39]:
missing_value_summary.to_csv(f"{output_dir}/missing_value_summary.csv", index=False)
rows_with_missing_values.to_csv(f"{output_dir}/rows_with_missing_values.csv", index=False)
missing_value_summary_with_missing_only.to_csv(f"{output_dir}/missing_values_only.csv", index=False)

print("Missing value output files have been saved.")

Missing value output files have been saved.

## 12. Warning
- == cannot be used for NaN
- Empty strings are NOT nulls

In [42]:
# Correct
df_employees["Score"].isnull()

0    False
1    False
2     True
3    False
4    False
5    False
6    False
7     True
Name: Score, dtype: bool

In [ ]:
# Wrong
df_employees["Score"] == None

## Summary

Today, I practiced checking missing values in pandas using `isnull()`.

I created a sample employee dataset with missing values and saved it as a CSV file. Then, I loaded the CSV file into a pandas DataFrame for missing value analysis.

I learned that `isnull()` creates a Boolean DataFrame where `True` represents a missing value and `False` represents an existing value.

I practiced counting missing values by column, counting total missing values in the entire DataFrame, and calculating missing value percentages by column.

I also practiced finding rows that contain at least one missing value, counting missing values by row, and creating a temporary `Missing_Value_Count` column.

In addition, I checked missing values in specific columns such as `Score` and `Department`, extracted complete rows with no missing values, and checked whether the entire DataFrame contains any missing values.

Finally, I created and saved missing value summary files as CSV files, including a full missing value summary, rows with missing values, and a summary containing only columns with missing values.

These concepts are important because checking missing values is one of the first steps in data cleaning, data analysis, and machine learning preparation.