# Imputing Missing Data with `.fillna()`
## **Objective:**
- Be able to group data by specific columns using pandas groupby(), and calculate summary statistics such as mean, sum, count, maximum, and minimum for each group.

## Today's Key Concepts
- df.fillna(value)
- df["Column"].fillna(value)
- df["Column"] = df["Column"].fillna(value)
- df.fillna({
    "Column1": value1,
    "Column2": value2
  })
- df["Numeric_Column"].fillna(df["Numeric_Column"].mean())
- df["Category_Column"].fillna(df["Category_Column"].mode()[0])

## Setting

In [51]:
import os
import pandas as pd
from pathlib import Path

# Create input and output folders
input_dir = "../assets/Week07/Day02/Input"
output_dir = "../assets/Week07/Day02/Output"

os.makedirs(input_dir, exist_ok=True)
os.makedirs(output_dir, exist_ok=True)

# Define input file path
input_file_path = f"{input_dir}/employee_data_with_missing_values.csv"

path = Path(input_file_path)

# Create sample employee data with missing values
employee_data = {
    "Employee_ID": [101, 102, 103, 104, 105, 106, 107, 108],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Henry"],
    "Department": ["Engineering", "Data", None, "Cloud", "Data", "Security", None, "Engineering"],
    "Experience": [5, 3, 7, None, 2, 8, 6, 1],
    "Score": [88, 92, None, 85, 67, 95, 90, None],
    "Status": ["Active", "Active", "Inactive", "Active", None, "Active", "Active", "Inactive"],
    "Remote": [True, True, False, True, None, False, True, True]
}
# Create DataFrame
df_employees = pd.DataFrame( employee_data )

# Save as CSV
df_employees.to_csv(input_file_path, index=False)


if path.exists():
    print("employee_data_with_missing_values.csv has been created.")
else:
    print("File not created.")

employee_data_with_missing_values.csv has been created.

In [13]:
# Read the employee CSV file
df_employees = pd.read_csv(
    "../assets/Week07/Day02/Input/employee_data_with_missing_values.csv"
)

# Display the DataFrame
df_employees

   Employee_ID     Name   Department  Experience  Score    Status Remote
0          101    Alice  Engineering         5.0   88.0    Active   True
1          102      Bob         Data         3.0   92.0    Active   True
2          103  Charlie          NaN         7.0    NaN  Inactive  False
3          104    David        Cloud         NaN   85.0    Active   True
4          105      Eva         Data         2.0   67.0       NaN    NaN
5          106    Frank     Security         8.0   95.0    Active  False
6          107    Grace          NaN         6.0   90.0    Active   True
7          108    Henry  Engineering         1.0    NaN  Inactive   True

## <u>fillna()</u>
- fillna() is a pandas function used to fill missing values, or NaN values, with specified alternative values.

&nbsp;&nbsp;&nbsp;&nbsp;e.g.) Replace NaN to "Unknown"<br>
``` Python
df_employees["Department"] = df_employees["Department"].fillna("Unknown")
```

- Checking Missing Values

In [8]:
df_employees.isnull().sum()

Employee_ID    0
Name           0
Department     2
Experience     1
Score          2
Status         1
Remote         1
dtype: int64

### 01. Replacing NaN in a specific column with a fixed value
- NaN in Department -> Unknown

In [11]:
df_department_filled = df_employees.copy()
df_department_filled["Department"] = df_department_filled["Department"].fillna("Unknown")

df_department_filled

   Employee_ID     Name   Department  Experience  Score    Status Remote
0          101    Alice  Engineering         5.0   88.0    Active   True
1          102      Bob         Data         3.0   92.0    Active   True
2          103  Charlie      Unknown         7.0    NaN  Inactive  False
3          104    David        Cloud         NaN   85.0    Active   True
4          105      Eva         Data         2.0   67.0       NaN    NaN
5          106    Frank     Security         8.0   95.0    Active  False
6          107    Grace      Unknown         6.0   90.0    Active   True
7          108    Henry  Engineering         1.0    NaN  Inactive   True

In [12]:
df_department_filled.isnull().sum()

Employee_ID    0
Name           0
Department     0
Experience     1
Score          2
Status         1
Remote         1
dtype: int64

### 02. Replacing NaN in a numeric column with the mean value.

In [18]:
df_score_mean_filled = df_employees.copy()
average_score = df_score_mean_filled["Score"].mean()

df_score_mean_filled = df_score_mean_filled["Score"].fillna(round(average_score, 2))
df_score_mean_filled

0    88.00
1    92.00
2    86.17
3    85.00
4    67.00
5    95.00
6    90.00
7    86.17
Name: Score, dtype: float64

### 03. Replacing NaN in a numeric column with the memian value.

In [22]:
df_experience_median_filled = df_employees.copy()
median_experiment = df_experience_median_filled["Experience"].median()
df_experience_median_filled = df_experience_median_filled["Experience"].fillna(median_experiment)

df_experience_median_filled

0    5.0
1    3.0
2    7.0
3    5.0
4    2.0
5    8.0
6    6.0
7    1.0
Name: Experience, dtype: float64

### 04. Imputing a String Column with the Mode (.mode())
- Since string columns cannot be averaged, you can fill missing values with the most frequent value using the `.mode()` function.
- `.mode()` returns a series, so [0] is used to retrieve the most common value

In [28]:
df_status_mode_filled = df_employees.copy()

most_common_status = df_status_mode_filled["Status"].mode()[0]

print(f"The most common value is {most_common_status}.")

df_status_mode_filled["Status"] = df_status_mode_filled["Status"].fillna(most_common_status)

df_status_mode_filled

The most common value is Active.

   Employee_ID     Name   Department  Experience  Score    Status Remote
0          101    Alice  Engineering         5.0   88.0    Active   True
1          102      Bob         Data         3.0   92.0    Active   True
2          103  Charlie          NaN         7.0    NaN  Inactive  False
3          104    David        Cloud         NaN   85.0    Active   True
4          105      Eva         Data         2.0   67.0    Active    NaN
5          106    Frank     Security         8.0   95.0    Active  False
6          107    Grace          NaN         6.0   90.0    Active   True
7          108    Henry  Engineering         1.0    NaN  Inactive   True

### 05. Filling a Boolean Column

In [37]:
df_remote_filled = df_employees.copy()

# Replacing NaN to False. This is just a practice.
df_remote_filled["Remote"] = df_remote_filled["Remote"].astype(bool).fillna(False)

df_remote_filled

   Employee_ID     Name   Department  Experience  Score    Status  Remote
0          101    Alice  Engineering         5.0   88.0    Active    True
1          102      Bob         Data         3.0   92.0    Active    True
2          103  Charlie          NaN         7.0    NaN  Inactive   False
3          104    David        Cloud         NaN   85.0    Active    True
4          105      Eva         Data         2.0   67.0       NaN    True
5          106    Frank     Security         8.0   95.0    Active   False
6          107    Grace          NaN         6.0   90.0    Active    True
7          108    Henry  Engineering         1.0    NaN  Inactive    True

### 06. Fill up multiple columns at once: Use a dictionary
- Department → "Unknown"
- Experience → median
- Score → mean
- Status → mode
- Remote → False

In [43]:
df_filled = df_employees.copy()

df_filled["Remote"] = df_filled["Remote"].astype(bool)

# Calculate fill values
experience_median = df_filled["Experience"].median()
score_mean = round(df_filled["Score"].mean(), 2)
status_mode = df_filled["Status"].mode()[0]

# Fill missing values by column
df_filled = df_filled.fillna(
    {
        "Department": "Unknown",
        "Experience": experience_median,
        "Score": score_mean,
        "Status": status_mode,
        "Remote": False
    }
)

df_filled

   Employee_ID     Name   Department  Experience  Score    Status  Remote
0          101    Alice  Engineering         5.0  88.00    Active    True
1          102      Bob         Data         3.0  92.00    Active    True
2          103  Charlie      Unknown         7.0  86.17  Inactive   False
3          104    David        Cloud         5.0  85.00    Active    True
4          105      Eva         Data         2.0  67.00    Active    True
5          106    Frank     Security         8.0  95.00    Active   False
6          107    Grace      Unknown         6.0  90.00    Active    True
7          108    Henry  Engineering         1.0  86.17  Inactive    True

### 07. Check if all NaNs are replaced
- Use `.isnull().sum()`

In [44]:
df_filled.isnull().sum()

Employee_ID    0
Name           0
Department     0
Experience     0
Score          0
Status         0
Remote         0
dtype: int64

In [47]:
# Create missing value counts before fillna
missing_before = df_employees.isnull().sum()

# Create missing value counts after fillna
missing_after = df_filled.isnull().sum()

# Create fillna summary DataFrame
fillna_summary = pd.DataFrame({
    "Column": df_employees.columns,
    "Missing_Before": missing_before.values,
    "Missing_After": missing_after.values
})

fillna_summary

        Column  Missing_Before  Missing_After
0  Employee_ID               0              0
1         Name               0              0
2   Department               2              0
3   Experience               1              0
4        Score               2              0
5       Status               1              0
6       Remote               1              0

In [53]:
# Define output file paths
filled_file_path = f"{output_dir}/employee_data_filled.csv"
fillna_summary_file_path = f"{output_dir}/fillna_summary.csv"

# Save filled DataFrame
df_filled.to_csv(filled_file_path, index=False)
filled_csv_file_path = Path(filled_file_path)

#Save fillna summary
fillna_summary.to_csv(fillna_summary_file_path, index=False)
fillna_summary_csv_path  = Path(fillna_summary_file_path)

if filled_csv_file_path.exists() and fillna_summary_csv_path:
    print("Filled data and fillna summary files have been saved.")
else:
    print("Files not created.")

Filled data and fillna summary files have been saved.

## Practice Problems

### Practice Dataset — Customer Orders

In [55]:
# Create practice dataset with missing values
order_data = {
    "Order_ID": [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008],
    "Customer": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Henry"],
    "Region": ["East", "West", None, "South", "East", None, "West", "South"],
    "Order_Amount": [250, None, 180, 320, None, 500, 410, None],
    "Discount": [10, 5, None, 15, 0, None, 20, 10],
    "Payment_Method": ["Credit Card", None, "PayPal", "Credit Card", "Cash", "Credit Card", None, "PayPal"],
    "Delivered": [True, True, False, None, True, False, True, None]
}

df_orders = pd.DataFrame(order_data)

df_orders

   Order_ID Customer Region  Order_Amount  Discount Payment_Method Delivered
0      1001    Alice   East         250.0      10.0    Credit Card      True
1      1002      Bob   West           NaN       5.0           None      True
2      1003  Charlie   None         180.0       NaN         PayPal     False
3      1004    David  South         320.0      15.0    Credit Card      None
4      1005      Eva   East           NaN       0.0           Cash      True
5      1006    Frank   None         500.0       NaN    Credit Card     False
6      1007    Grace   West         410.0      20.0           None      True
7      1008    Henry  South           NaN      10.0         PayPal      None

### Practice 1 — Check Missing Values
#### Goal: Check which columns have missing values before using fillna().
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Create a missing value count summary for df_orders.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Expected output should show each column and its missing value count.<br>

In [59]:
df_orders_summary = df_orders.isnull().sum()
df_orders_summary

Order_ID          0
Customer          0
Region            2
Order_Amount      3
Discount          2
Payment_Method    2
Delivered         2
dtype: int64

### Practice 2 — Fill Region with "Unknown"
#### Goal: Practice filling a categorical column with a fixed value.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Fill missing values in Region with:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Unknown<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;Save the result into a new DataFrame called:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;df_orders_filled<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;Do not modify df_orders directly.

In [61]:
# Fill missing values in Regions with "Unknown"
df_orders_filled = df_orders.copy()

df_orders_filled["Region"] = df_orders_filled["Region"].fillna("Unknown")
df_orders_filled

   Order_ID Customer   Region  Order_Amount  Discount Payment_Method Delivered
0      1001    Alice     East         250.0      10.0    Credit Card      True
1      1002      Bob     West           NaN       5.0           None      True
2      1003  Charlie  Unknown         180.0       NaN         PayPal     False
3      1004    David    South         320.0      15.0    Credit Card      None
4      1005      Eva     East           NaN       0.0           Cash      True
5      1006    Frank  Unknown         500.0       NaN    Credit Card     False
6      1007    Grace     West         410.0      20.0           None      True
7      1008    Henry    South           NaN      10.0         PayPal      None

### Practice 3 — Fill Order_Amount with the Median
#### Goal: Practice filling a numeric column with a median value.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Calculate the median of Order_Amount.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Fill missing values in Order_Amount with that median.

In [65]:
df_order_amount_filled = df_orders.copy()

order_amount_median = df_order_amount_filled["Order_Amount"].median()
print(f"The median value: {order_amount_median}")

df_order_amount_filled["Order_Amount"] = df_order_amount_filled["Order_Amount"].fillna(order_amount_median)

df_order_amount_filled

The median value: 320.0

   Order_ID Customer Region  Order_Amount  Discount Payment_Method Delivered
0      1001    Alice   East         250.0      10.0    Credit Card      True
1      1002      Bob   West         320.0       5.0           None      True
2      1003  Charlie   None         180.0       NaN         PayPal     False
3      1004    David  South         320.0      15.0    Credit Card      None
4      1005      Eva   East         320.0       0.0           Cash      True
5      1006    Frank   None         500.0       NaN    Credit Card     False
6      1007    Grace   West         410.0      20.0           None      True
7      1008    Henry  South         320.0      10.0         PayPal      None

### Practice 4 — Fill Discount with 0
#### Goal: Practice choosing a value based on column meaning.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Fill missing values in Discount with 0.<br>

&nbsp;&nbsp;&nbsp;&nbsp;Reason:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If Discount is missing, assume no discount was applied.

In [67]:
df_discount_filled = df_orders.copy()

df_discount_filled["Discount"] = df_discount_filled["Discount"].fillna(0)
df_discount_filled

   Order_ID Customer Region  Order_Amount  Discount Payment_Method Delivered
0      1001    Alice   East         250.0      10.0    Credit Card      True
1      1002      Bob   West           NaN       5.0           None      True
2      1003  Charlie   None         180.0       0.0         PayPal     False
3      1004    David  South         320.0      15.0    Credit Card      None
4      1005      Eva   East           NaN       0.0           Cash      True
5      1006    Frank   None         500.0       0.0    Credit Card     False
6      1007    Grace   West         410.0      20.0           None      True
7      1008    Henry  South           NaN      10.0         PayPal      None

### Practice 5 — Fill Payment_Method with the Most Frequent Value
#### Goal: Practice filling a categorical column with the mode.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Find the most common value in Payment_Method.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Fill missing values in Payment_Method with that value.

In [72]:
df_pay_method_filled = df_orders.copy()

most_used_pay_method = df_pay_method_filled["Payment_Method"].mode()[0]

df_pay_method_filled["Payment_Method"] = df_pay_method_filled["Payment_Method"].fillna(most_used_pay_method)

df_pay_method_filled

   Order_ID Customer Region  Order_Amount  Discount Payment_Method Delivered
0      1001    Alice   East         250.0      10.0    Credit Card      True
1      1002      Bob   West           NaN       5.0    Credit Card      True
2      1003  Charlie   None         180.0       NaN         PayPal     False
3      1004    David  South         320.0      15.0    Credit Card      None
4      1005      Eva   East           NaN       0.0           Cash      True
5      1006    Frank   None         500.0       NaN    Credit Card     False
6      1007    Grace   West         410.0      20.0    Credit Card      True
7      1008    Henry  South           NaN      10.0         PayPal      None

### Practice 6 — Fill Delivered with `False`
#### Goal: Practice filling a boolean column.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Fill missing values in Delivered with `False`<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;Reason:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If delivery status is missing, assume it has not been delivered yet.

In [75]:
df_delivered_filled = df_orders.copy()

df_delivered_filled["Delivered"] = df_delivered_filled["Delivered"].astype(bool).fillna(False)

df_delivered_filled

   Order_ID Customer Region  Order_Amount  Discount Payment_Method  Delivered
0      1001    Alice   East         250.0      10.0    Credit Card       True
1      1002      Bob   West           NaN       5.0           None       True
2      1003  Charlie   None         180.0       NaN         PayPal      False
3      1004    David  South         320.0      15.0    Credit Card      False
4      1005      Eva   East           NaN       0.0           Cash       True
5      1006    Frank   None         500.0       NaN    Credit Card      False
6      1007    Grace   West         410.0      20.0           None       True
7      1008    Henry  South           NaN      10.0         PayPal      False

### Practice 7 — Create a Before/After Missing Value Summary
#### Goal: Practice comparing missing values before and after filling.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Create a DataFrame called:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;order_fillna_summary<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;It should have these columns:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Column<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Missing_Before<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Missing_After<br>

In [113]:
df_orders_copy = df_orders.copy()
df_orders_copy["Delivered"] = df_orders_copy["Delivered"].astype(bool)

order_amount_median = df_orders_copy["Order_Amount"].median()
most_payment_method = df_orders_copy["Payment_Method"].mode()[0]

missing_before = df_orders_copy.isnull().sum()

missing_after = df_orders_copy.fillna({
    "Region" : "Unknown",
    "Order_Amount" : order_amount_median,
    "Discount" : 0,
    "Payment_Method" : most_payment_method,
    "Delivered" : False
}).isnull().sum()

order_fillna_summary = pd.DataFrame( {
    "Columns" : df_orders_copy.columns,
    "Missing_Before" : missing_before.values,
    "Missing_After" : missing_after.values
})
order_fillna_summary

          Columns  Missing_Before  Missing_After
0        Order_ID               0              0
1        Customer               0              0
2          Region               2              0
3    Order_Amount               3              0
4        Discount               2              0
5  Payment_Method               2              0
6       Delivered               0              0

### Practice 8 — Verify That All Missing Values Are Filled
#### Goal: Confirm that there are no missing values left.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Print the total number of missing values after filling.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Expected result: 0

In [105]:
print(missing_after.isnull().sum().sum())

0

### Practice 9 — Add a New Column After Filling
#### Goal: Combine Week 6 Day 3 knowledge with `fillna()`.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;After filling missing values, create a new column called:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Final_Amount<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;Formula:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Final_Amount = Order_Amount - Discount

In [112]:
add_final_amount = df_orders_copy.fillna({
    "Region" : "Unknown",
    "Order_Amount" : order_amount_median,
    "Discount" : 0,
    "Payment_Method" : most_payment_method,
    "Delivered" : False
})

add_final_amount["Final_Amount"] = add_final_amount["Order_Amount"] - add_final_amount["Discount"]
add_final_amount

   Order_ID Customer   Region  Order_Amount  Discount Payment_Method  Delivered  Final_Amount
0      1001    Alice     East         250.0      10.0    Credit Card       True         240.0
1      1002      Bob     West         320.0       5.0    Credit Card       True         315.0
2      1003  Charlie  Unknown         180.0       0.0         PayPal      False         180.0
3      1004    David    South         320.0      15.0    Credit Card      False         305.0
4      1005      Eva     East         320.0       0.0           Cash       True         320.0
5      1006    Frank  Unknown         500.0       0.0    Credit Card      False         500.0
6      1007    Grace     West         410.0      20.0    Credit Card       True         390.0
7      1008    Henry    South         320.0      10.0         PayPal      False         310.0

### Practice 10 — Save the Cleaned Order Data
#### Goal: Practice saving cleaned data.
##### <u>Requirements</u>
&nbsp;&nbsp;&nbsp;&nbsp;Save the filled order DataFrame as:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;../assets/Week07/Day02/Output/customer_orders_filled.csv<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;Save the before/after summary as:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;../assets/Week07/Day02/Output/customer_orders_fillna_summary.csv

In [115]:
# add_final_amount
add_final_amount.to_csv(f"{output_dir}/customer_orders_filled.csv")

# order_fillna_summary
add_final_amount.to_csv(f"{output_dir}/customer_orders_fillna_summary.csv")

## Summary

Today, I practiced filling missing values in pandas using `fillna()`.

I learned how to fill missing values with fixed values, mean values, median values, mode values, and different values for different columns.

I practiced filling categorical columns such as `Department` with `"Unknown"`, numeric columns such as `Score` and `Experience` with calculated values, and boolean columns such as `Remote` with `False`.

I also learned that `fillna()` does not permanently modify the original DataFrame unless the result is assigned back to a variable or column.

Finally, I created a before-and-after missing value summary and saved the filled DataFrame and summary results as CSV files.

These concepts are important because filling missing values is a common data cleaning step before analysis, reporting, and machine learning workflows.